"""Tests for auto-stale-paths ADR-270 enforcement."""

from __future__ import annotations

import json
import os
import importlib.util
import sys
from pathlib import Path

from src.lib.ops_protocol import OpsContext


def _load_module():
    module_file = Path(__file__).resolve().parents[2] / "scripts" / "ops" / "stale_paths.py"
    spec = importlib.util.spec_from_file_location("stale_paths", module_file)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules["stale_paths"] = mod
    spec.loader.exec_module(mod)
    return mod


stale_paths = _load_module()


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _ctx(project_root: Path, **kwargs) -> OpsContext:
    return OpsContext(project_root=project_root, **kwargs)


def test_scan_detects_adr270_drift_classes_and_skips_archival_docs(tmp_path: Path):
    repo_root = tmp_path / "repo"
    runtime_path = "runtime" + "/coverage/coverage-summary.json"
    data_path = "augur" + "/" + "data/actions/status.yaml"
    mcp_path = "augur" + "/" + "mcp/__init__.py"

    _write(
        repo_root / ".github" / "scripts" / "legacy_runtime.py",
        f'coverage_file = "{runtime_path}"\n',
    )
    _write(
        repo_root / "src" / "legacy_data.ts",
        f'const legacyPath = "{data_path}";\n',
    )
    _write(
        repo_root / "plugins" / "observability" / "skills" / "demo" / "scripts" / "legacy_mcp.py",
        f'legacy = "{mcp_path}"\n',
    )
    _write(
        repo_root / "plugins" / "observability" / "skills" / "demo" / "augur" / "README.md",
        "# demo\n\nGenerated by ADR-270 migration. Update from SKILL.md.\n",
    )
    _write(
        repo_root / "docs" / "decisions" / "ADR-test.md",
        "Historical note about runtime logs and augur data paths.\n",
    )

    result = stale_paths.scan(_ctx(repo_root))

    actions = {issue["action"] for issue in result.issues}
    files = {issue["file"] for issue in result.issues}

    assert actions == {
        "legacy-runtime-path",
        "legacy-augur-data-path",
        "legacy-augur-mcp-path",
    }
    assert "docs/decisions/ADR-test.md" not in files
    assert "documentation issue(s) tracked separately" in result.summary
    assert result.severity == "warning"
    assert result.health == "degraded"


def test_scan_honors_intentional_skip_marker(tmp_path: Path):
    repo_root = tmp_path / "repo"
    _write(
        repo_root / "src" / "skip_me.py",
        '# INTENTIONAL_SKIP(adr-269): legacy path kept for fixture coverage\n'
        'PATH = "runtime" + "/logs/test.log"\n',
    )

    result = stale_paths.scan(_ctx(repo_root))

    assert result.issues == []
    assert result.health == "verified"


def test_scan_ignores_runtime_slash_inside_python_docstring(tmp_path: Path):
    repo_root = tmp_path / "repo"
    _write(
        repo_root / "src" / "mcp" / "harness.py",
        '"""Harness helpers.\n\n'
        "The snapshot is generated runtime/cache state; canonical facts remain in source.\n"
        '"""\n\n'
        'ACTIVE_RUNTIME = "runtime/cache/state.json"\n',
    )

    result = stale_paths.scan(_ctx(repo_root))

    assert len(result.issues) == 1
    assert result.issues[0]["line"] == 6
    assert result.issues[0]["line_text"] == 'ACTIVE_RUNTIME = "runtime/cache/state.json"'


def test_scan_skips_generated_npm_package_lock(tmp_path: Path):
    repo_root = tmp_path / "repo"
    _write(
        repo_root / "apps" / "dashboard" / "package-lock.json",
        '{"resolved": "https://registry.npmjs.org/@babel/runtime/-/runtime-7.29.2.tgz"}\n',
    )

    result = stale_paths.scan(_ctx(repo_root))

    assert result.issues == []
    assert result.health == "verified"


def test_scan_skips_sync_agent_generated_surfaces(tmp_path: Path):
    repo_root = tmp_path / "repo"

    generated_surfaces = [
        repo_root / ".antigravity" / "workflows" / "ops-loops.md",
        repo_root / ".claude" / "skills" / "save" / "SKILL.md",
        repo_root / ".gemini" / "skills" / "ops-import" / "SKILL.md",
        repo_root / "docs" / "agent-topics" / "WORKFLOWS.md",
        repo_root / "AGENTS.md",
        repo_root / "CLAUDE.md",
        repo_root / "CODEX.md",
    ]
    for path in generated_surfaces:
        _write(path, 'legacy = "runtime/logs/dev-server.log"\n')

    _write(
        repo_root / ".github" / "scripts" / "legacy_runtime.py",
        'coverage_file = "runtime/coverage/coverage-summary.json"\n',
    )

    result = stale_paths.scan(_ctx(repo_root))

    assert len(result.issues) == 1
    assert result.issues[0]["file"] == ".github/scripts/legacy_runtime.py"
    assert result.issues[0]["action"] == "legacy-runtime-path"


def test_scan_ignores_staging_release_payloads(tmp_path: Path):
    repo_root = tmp_path / "repo"

    _write(
        repo_root / "staging" / "r2" / "README.md",
        'legacy = "runtime/logs/dev-server.log"\n',
    )
    _write(
        repo_root / "staging" / "r2" / "skills" / "content" / "SKILL.md",
        'legacy = "runtime/logs/dev-server.log"\n',
    )
    _write(
        repo_root / "src" / "real_issue.py",
        'legacy = "runtime/logs/dev-server.log"\n',
    )

    actionable, documentation = stale_paths._collect_drift_issues(repo_root)
    result = stale_paths.scan(_ctx(repo_root))

    assert len(actionable) == 1
    assert actionable[0]["file"] == "src/real_issue.py"
    assert documentation == []
    assert len(result.issues) == 1
    assert result.issues[0]["file"] == "src/real_issue.py"


def test_scan_skips_test_directories_and_known_legacy_utilities(tmp_path: Path):
    repo_root = tmp_path / "repo"

    _write(
        repo_root / "plugins" / "demo" / "augur" / "tests" / "test_fixture.py",
        'legacy = "runtime/logs/dev-server.log"\n',
    )
    _write(
        repo_root / ".github" / "scripts" / "scan_stale_paths.py",
        'legacy = "augur/data/actions/status.yaml"\n',
    )
    _write(
        repo_root / "apps" / "dashboard" / "scripts" / "skill-scripts" / "generate_hardening_adr.py",
        'legacy = "skills/frontend/augur/data/hardening-reports/example.yaml"\n',
    )
    _write(
        repo_root / "src" / "real_issue.py",
        'legacy = "runtime/logs/dev-server.log"\n',
    )

    actionable, documentation = stale_paths._collect_drift_issues(repo_root)
    result = stale_paths.scan(_ctx(repo_root))

    assert len(actionable) == 1
    assert actionable[0]["file"] == "src/real_issue.py"
    assert documentation == []
    assert len(result.issues) == 1
    assert result.issues[0]["file"] == "src/real_issue.py"


def test_scan_skips_intentional_enforcement_scripts(tmp_path: Path):
    repo_root = tmp_path / "repo"

    _write(
        repo_root / ".github" / "scripts" / "validate_skill_structure.py",
        'pattern = r"\\skills/[^/]+/augur/data/"\n',
    )
    _write(
        repo_root / "scripts" / "check-skill-structure.sh",
        '*/augur/data/*) warn "augur/data/ is deprecated. Use assets/seeds/ instead." ;;\n',
    )
    _write(
        repo_root / "src" / "real_issue.py",
        'legacy = "runtime/logs/dev-server.log"\n',
    )

    actionable, documentation = stale_paths._collect_drift_issues(repo_root)
    result = stale_paths.scan(_ctx(repo_root))

    assert len(actionable) == 1
    assert actionable[0]["file"] == "src/real_issue.py"
    assert documentation == []
    assert len(result.issues) == 1
    assert result.issues[0]["file"] == "src/real_issue.py"
    assert result.issues[0]["action"] == "legacy-runtime-path"


def test_scan_ignores_python_docstrings_describing_runtime_helpers(tmp_path: Path):
    repo_root = tmp_path / "repo"

    _write(
        repo_root / "src" / "runtime_doc.py",
        '"""Return the runtime/config root for a supported client."""\n'
        'def helper() -> str:\n'
        '    return "ok"\n',
    )

    result = stale_paths.scan(_ctx(repo_root))

    assert result.issues == []


def test_fix_writes_structured_adr270_report(monkeypatch, tmp_path: Path):
    repo_root = tmp_path / "repo"
    state_root = tmp_path / "state"
    monkeypatch.setenv("AUGUR_STATE", str(state_root))

    _write(
        repo_root / ".github" / "workflows" / "legacy.yml",
        'path: runtime' + '/visual-regression/\n',
    )

    ctx = _ctx(repo_root)
    issues = stale_paths.scan(ctx).issues
    fix_result = stale_paths.fix(ctx, issues)
    report_path = state_root / "reports" / "adr270-enforcement-latest.json"

    assert fix_result.success is True
    assert report_path.exists()

    report = json.loads(report_path.read_text(encoding="utf-8"))
    assert report["summary"]["issue_count"] == 1
    assert report["summary"]["documentation_issue_count"] == 0
    assert report["summary"]["by_category"] == {"runtime": 1}
    assert report["issues"][0]["action"] == "legacy-runtime-path"


def test_fix_separates_documentation_drift_from_actionable_drift(monkeypatch, tmp_path: Path):
    repo_root = tmp_path / "repo"
    state_root = tmp_path / "state"
    monkeypatch.setenv("AUGUR_STATE", str(state_root))

    _write(
        repo_root / ".github" / "scripts" / "legacy_runtime.py",
        'coverage_file = "runtime/coverage/coverage-summary.json"\n',
    )
    _write(
        repo_root / "plugins" / "demo" / "SKILL.md",
        'This skill still references augur/data/actions/status.yaml\n',
    )

    ctx = _ctx(repo_root)
    scan_result = stale_paths.scan(ctx)
    report_result = stale_paths.fix(ctx, scan_result.issues)
    report_path = state_root / "reports" / "adr270-enforcement-latest.json"
    report = json.loads(report_path.read_text(encoding="utf-8"))

    assert report_result.success is True
    assert len(scan_result.issues) == 1
    assert "documentation issue(s) tracked separately" in scan_result.summary
    assert report["summary"]["issue_count"] == 1
    assert report["summary"]["documentation_issue_count"] == 1
    assert report["issues"][0]["file"] == ".github/scripts/legacy_runtime.py"
    assert report["documentation_issues"][0]["file"] == "plugins/demo/SKILL.md"


def test_fix_sed_replaces_legacy_dashboard_paths(tmp_path: Path):
    """fix() auto-replaces src/dashboard with apps/dashboard via sed."""
    repo_root = tmp_path / "repo"
    target = repo_root / "config" / "example.yaml"
    _write(target, 'dashboard_path: src/dashboard/components\n')

    ctx = _ctx(repo_root)
    issues = stale_paths.scan(ctx).issues
    assert len(issues) == 1
    assert issues[0]["fix_strategy"] == "sed"

    fix_result = stale_paths.fix(ctx, issues)
    assert fix_result.success is True
    assert len(fix_result.changes) == 1

    updated = target.read_text()
    assert "apps/dashboard/components" in updated
    assert "src/dashboard" not in updated


def test_declares_windows_auto_fix_capabilities():
    assert stale_paths.OPS_CAPABILITIES.platforms == ("cross_platform",)
    assert stale_paths.OPS_CAPABILITIES.windows_fix_mode == "auto_fix"


def test_fix_sed_replaces_src_lib_dashboard(tmp_path: Path):
    """fix() replaces the longer src/lib/dashboard path correctly."""
    repo_root = tmp_path / "repo"
    target = repo_root / "config" / "paths.ts"
    _write(target, 'const p = "src/lib/dashboard/utils";\n')

    ctx = _ctx(repo_root)
    issues = stale_paths.scan(ctx).issues
    assert len(issues) == 1
    assert issues[0]["fix_strategy"] == "sed"

    fix_result = stale_paths.fix(ctx, issues)
    assert fix_result.success is True
    updated = target.read_text()
    assert "apps/dashboard/utils" in updated
    assert "src/lib/dashboard" not in updated


def test_scan_ignores_canonical_apps_dashboard_path(tmp_path: Path):
    """apps/dashboard is canonical and must not be reported as drift."""
    repo_root = tmp_path / "repo"
    _write(
        repo_root / ".github" / "scripts" / "uses_dashboard.py",
        'dashboard = "apps/dashboard/components"\n',
    )

    result = stale_paths.scan(_ctx(repo_root))

    assert result.issues == []
    assert result.health == "verified"


def test_fix_mixed_sed_and_report(monkeypatch, tmp_path: Path):
    """fix() handles both sed-fixable and report-only issues in one pass."""
    repo_root = tmp_path / "repo"
    state_root = tmp_path / "state"
    monkeypatch.setenv("AUGUR_STATE", str(state_root))

    _write(
        repo_root / "config" / "example.yaml",
        'path: src/dashboard/app\n',
    )
    _write(
        repo_root / ".github" / "workflows" / "legacy.yml",
        'path: runtime' + '/visual-regression/\n',
    )

    ctx = _ctx(repo_root)
    issues = stale_paths.scan(ctx).issues
    strategies = {i["fix_strategy"] for i in issues}
    assert "sed" in strategies
    assert "report" in strategies

    fix_result = stale_paths.fix(ctx, issues)
    assert fix_result.success is True
    # Dashboard path was sed-fixed
    assert "apps/dashboard/app" in (repo_root / "config" / "example.yaml").read_text()
    # Runtime issue was reported
    report_path = state_root / "reports" / "adr270-enforcement-latest.json"
    assert report_path.exists()


def test_scan_dry_run_d0_reuses_cached_report(monkeypatch, tmp_path: Path):
    repo_root = tmp_path / "repo"
    state_root = tmp_path / "state"
    repo_root.mkdir()
    monkeypatch.setenv("AUGUR_STATE", str(state_root))
    report_dir = state_root / "reports"
    report_dir.mkdir(parents=True)
    report_path = report_dir / "adr270-enforcement-latest.json"
    report_path.write_text(
        json.dumps(
            {
                "summary": {
                    "issue_count": 2,
                    "documentation_issue_count": 5,
                },
                "issues": [],
                "documentation_issues": [],
            }
        ),
        encoding="utf-8",
    )

    result = stale_paths.scan(_ctx(repo_root, dry_run=True, difficulty=0))

    assert len(result.issues) == 2
    assert "[cached report]" in result.summary
    assert "5 documentation issue(s)" in result.summary
    assert result.health == "degraded"


def test_scan_dry_run_d0_ignores_stale_cached_report_when_newer_hardening_omits_category(
    monkeypatch,
    tmp_path: Path,
):
    repo_root = tmp_path / "repo"
    state_root = tmp_path / "state"
    repo_root.mkdir()
    monkeypatch.setenv("AUGUR_STATE", str(state_root))

    report_dir = state_root / "reports"
    report_dir.mkdir(parents=True)
    stale_report = report_dir / "adr270-enforcement-latest.json"
    stale_report.write_text(
        json.dumps(
            {
                "summary": {
                    "issue_count": 2,
                    "documentation_issue_count": 5,
                },
                "issues": [],
                "documentation_issues": [],
            }
        ),
        encoding="utf-8",
    )

    adaptive_report_dir = state_root / "adaptive" / "reports"
    adaptive_report_dir.mkdir(parents=True)
    hardening_report = adaptive_report_dir / "hardening-latest.json"
    hardening_report.write_text(
        json.dumps(
            {
                "categories": [
                    {
                        "name": "auto-tab-registry",
                        "actionable_count": 0,
                        "outcome": "clean",
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    future = Path(__file__).resolve().stat().st_mtime + 1000
    os.utime(stale_report, (1, 1))
    os.utime(hardening_report, (future, future))

    result = stale_paths.scan(_ctx(repo_root, dry_run=True, difficulty=0))

    assert result.issues == []
    assert "[cached report]" not in result.summary
    assert result.health == "verified"


def test_scan_dry_run_d0_prefers_newer_hardening_status(monkeypatch, tmp_path: Path):
    repo_root = tmp_path / "repo"
    state_root = tmp_path / "state"
    repo_root.mkdir()
    monkeypatch.setenv("AUGUR_STATE", str(state_root))

    report_dir = state_root / "reports"
    report_dir.mkdir(parents=True)
    stale_report = report_dir / "adr270-enforcement-latest.json"
    stale_report.write_text(
        json.dumps(
            {
                "summary": {
                    "issue_count": 2,
                    "documentation_issue_count": 5,
                },
                "issues": [],
                "documentation_issues": [],
            }
        ),
        encoding="utf-8",
    )

    adaptive_report_dir = state_root / "adaptive" / "reports"
    adaptive_report_dir.mkdir(parents=True)
    hardening_report = adaptive_report_dir / "hardening-latest.json"
    hardening_report.write_text(
        json.dumps(
            {
                "categories": [
                    {
                        "name": "auto-stale-paths",
                        "actionable_count": 0,
                        "outcome": "clean",
                    }
                ]
            }
        ),
        encoding="utf-8",
    )
    future = Path(__file__).resolve().stat().st_mtime + 1000
    os.utime(stale_report, (1, 1))
    os.utime(hardening_report, (future, future))

    result = stale_paths.scan(_ctx(repo_root, dry_run=True, difficulty=0))

    assert result.issues == []
    assert "[latest hardening report]" in result.summary
    assert result.health == "verified"
