#!/usr/bin/env python3
"""
Hardening ADR Generator (ADR-065)

Reads a hardening audit YAML report and generates a complete ADR markdown file
with audit summary, wow effect, phased decision, team-splitting, and
implementation prompt.

Usage:
    python3 project-brain/capabilities/skills/frontend/scripts/generate_hardening_adr.py \
        --audit "~/Library/Application Support/Augur/state/hardening/career/career-skill/career_20260211.yaml"

Output:
    get_adr_dir()/ADR-{NNN}-{hub}-hardening.md
"""

import argparse
import sys
from pathlib import Path
from typing import Any

# Ensure project root is on sys.path for imports
sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from src.config.paths import get_project_root

# ---------------------------------------------------------------------------
# Re-exports: all public symbols from sub-modules remain importable from here.
# ---------------------------------------------------------------------------
from ._hardening_constants import (  # noqa: F401
    DIMENSION_AGENT_MAP,
    SCOPE_LABELS,
    TIER_MODEL_MAP,
)
from ._hardening_report import (  # noqa: F401
    _action_signal_conflict_note,
    _dimension_label_map,
    _normalize_scope,
    _normalize_skip_dimensions,
    _parse_action_ratio,
    find_next_adr_number,
    get_selected_dimensions,
    get_user_choices,
    load_audit_report,
    parse_adr_number_from_path,
    parse_adr_slug_from_path,
)
from ._hardening_sections import (  # noqa: F401
    _build_execution_phases,
    _group_dimensions_by_phase,
    generate_audit_summary,
    generate_consequences,
    generate_context,
    generate_decision,
    generate_metadata,
    generate_wow_effect_section,
)
from ._hardening_implementation import (  # noqa: F401
    _infer_files_for_dimension,
    generate_implementation_prompt,
)


def _out(*args: object, **kwargs: object) -> None:
    sep = kwargs.get("sep", " ")
    end = kwargs.get("end", "\n")
    file = kwargs.get("file", sys.stdout)
    file.write(sep.join(str(arg) for arg in args) + str(end))


# ---------------------------------------------------------------------------
# ADR Assembly
# ---------------------------------------------------------------------------


def generate_adr(report: dict[str, Any], adr_number: int) -> str:
    """Assemble the full ADR markdown from all sections."""
    hub_title = report.get("audit", {}).get("hub_title", "Unknown")

    sections = [
        generate_metadata(adr_number, hub_title),
        generate_audit_summary(report),
        generate_wow_effect_section(report),
        generate_context(report),
        generate_decision(report),
    ]

    notes = get_user_choices(report).get("notes", "")
    if notes:
        sections.extend(
            [
                "## User Notes",
                "",
                notes,
                "",
            ]
        )

    audit = report.get("audit", {}) or {}
    report_id = str(audit.get("report_id", audit.get("hub_id", "unknown")) or "unknown")
    scope = str(audit.get("scope", "hub") or "hub")
    route_prefix = str(audit.get("route_prefix", "") or "")
    if scope == "extension":
        audit_ref = f"`{report_id}` extension audit ({route_prefix})"
    else:
        audit_ref = f"`{report_id}` hub audit"

    sections.extend(
        [
            generate_consequences(report),
            "## Alternatives Considered",
            "",
            "This ADR was auto-generated by the dashboard hardening audit engine (ADR-065).",
            "No manual alternatives were evaluated.",
            "",
            "## References",
            "",
            "- ADR-065: Dashboard hardening workflow automation (parent)",
            f"- Audit report: {audit_ref}",
            f"- Audit timestamp: {audit.get('timestamp', '')}",
            "",
            generate_implementation_prompt(report, adr_number),
        ]
    )

    return "\n".join(sections)


# ---------------------------------------------------------------------------
# CLI Entry Point
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(
        description="Hardening ADR Generator (ADR-065)",
        epilog="Example: python3 %(prog)s --audit skills/frontend/augur/data/hardening-reports/career_20260211.yaml",
    )
    parser.add_argument(
        "--audit",
        required=True,
        help="Path to the hardening audit YAML report",
    )
    parser.add_argument(
        "--output",
        help="Custom output path for the ADR (default: auto-numbered in get_adr_dir())",
    )
    parser.add_argument(
        "--adr-number",
        type=int,
        help="Override ADR number (default: auto-detect next available)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print ADR to stdout without writing file",
    )

    args = parser.parse_args()

    from src.config.paths import get_runtime_dir
    from src.lib.adr_utils import get_adr_dir, upsert_adr_entry

    project_root = get_project_root()
    decisions_dir = get_adr_dir()

    # Load audit report
    audit_path = Path(args.audit)
    if not audit_path.is_absolute():
        audit_path = project_root / audit_path
    if not audit_path.exists():
        _out(f"Error: Audit file not found: {audit_path}", file=sys.stderr)
        sys.exit(1)

    _out(f"Loading audit report: {audit_path}")
    report = load_audit_report(audit_path)

    hub_id = report.get("audit", {}).get("hub_id", "unknown")
    adr_slug = str(report.get("audit", {}).get("report_id", hub_id) or hub_id).replace("_", "-")
    hub_title = report.get("audit", {}).get("hub_title", hub_id)

    # ADR-642/ADR-811: live ADRs no longer live as files in docs/adrs/ (now project-brain/decisions/adrs/). The hardening
    # ADR body is staged in the runtime extracts dir for human review; the
    # durable record is added to the central JSON index.
    runtime_extracts = get_runtime_dir() / "adr-extracts"
    if args.output:
        output_path = Path(args.output)
    else:
        output_path = runtime_extracts / "{num_dir}" / f"ADR-{{num}}-{adr_slug}-hardening.md"
    output_slug = parse_adr_slug_from_path(output_path) if args.output else None
    adr_doc_slug = output_slug or adr_slug

    # Determine ADR number
    if args.adr_number:
        adr_number = args.adr_number
    else:
        inferred_from_output = parse_adr_number_from_path(output_path) if args.output else None
        if inferred_from_output is not None:
            adr_number = inferred_from_output
        else:
            adr_number = find_next_adr_number(decisions_dir)

    _out(f"Generating ADR-{adr_number:03d}: {hub_title} Hardening")

    report.setdefault("audit", {})["adr_slug"] = adr_doc_slug

    # Generate ADR content
    adr_content = generate_adr(report, adr_number)

    if args.dry_run:
        _out("\n" + adr_content)
        return

    # Resolve output path (default: runtime extracts dir).
    if not args.output:
        runtime_dir = runtime_extracts / f"ADR-{adr_number:03d}"
        runtime_dir.mkdir(parents=True, exist_ok=True)
        output_path = runtime_dir / f"ADR-{adr_number:03d}-{adr_doc_slug}-hardening.md"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(adr_content, encoding="utf-8")

    _out(f"ADR body staged at: {output_path}")

    # Persist a stub record in the central index. The user reviews the body
    # and promotes it via /adr write or /adr implement when ready.
    decision_summary = (report.get("interpretation") or "Hardening ADR").strip()
    upsert_adr_entry(
        decisions_dir,
        {
            "adr_number": f"ADR-{adr_number:03d}",
            "title": f"{hub_title} Hardening",
            "state": "live",
            "status": "Proposed",
            "date": (report.get("audit", {}) or {}).get("timestamp", "")[:10],
            "deciders": ["Hardening Engine"],
            "related": ["ADR-065"],
            "hub": hub_id,
            "tags": ["hardening", hub_id],
            "decision_summary": decision_summary,
            "status_notes": f"Generated from {audit_path.name}",
            "impact": {
                "paths_renamed": [],
                "apis_changed": [],
                "patterns_deprecated": [],
                "files_affected": [],
            },
            "spec_file": None,
            "plan_file": None,
            "superseded_by": None,
        },
    )
    _out(f"\nComposite score: {report.get('composite_score', 0)}/100")
    _out(f"Interpretation: {report.get('interpretation', 'unknown')}")

    # Count phases with work
    dimensions = get_selected_dimensions(report)
    phases = _build_execution_phases(report, dimensions)
    for phase in phases:
        phase_num = int(phase.get("display_num", 0) or 0)
        phase_key = str(phase.get("key", ""))
        if phase_key == "reconciliation":
            _out(f"Phase {phase_num}: scoring reconciliation")
            continue
        dims = phase.get("dims", [])
        _out(f"Phase {phase_num}: {len(dims)} dimensions")


if __name__ == "__main__":
    main()
