"""
Skill Porter Operations

High-level import/export operations: analyze, apply, export.
Also handles dev metadata scaffolding and data templates.
"""

from __future__ import annotations

import shutil
import sys
import textwrap
import zipfile
from datetime import datetime
from pathlib import Path
from typing import Any

from porter_utils import (
    PACKAGES_DIR,
    REPO_ROOT,
    iter_copy_candidates,
    is_kebab_case,
    safe_mkdir,
    should_ignore_path,
    slugify,
    utc_now_iso,
    IGNORED_DIRS,
    run,
)
from porter_markdown import (
    extract_storage_tree,
    extract_title,
    normalize_description,
    parse_frontmatter,
    parse_storage_paths,
    trim_skill_markdown,
)
from porter_source import SourceContext


def compute_dest_slug(ctx: SourceContext) -> tuple[str, str, str]:
    raw = ctx.skill_md.read_text(encoding="utf-8")
    fm, body, _ = parse_frontmatter(raw)
    name = fm.get("name")
    if isinstance(name, str) and name.strip():
        proposed = slugify(name.strip())
    else:
        proposed = slugify(ctx.skill_root.name)
    title = extract_title(body, proposed)
    description = ""
    if isinstance(fm.get("description"), str):
        description = normalize_description(fm["description"])  # type: ignore[arg-type]
    return proposed, title, description


def ensure_dev_metadata(skill_dir: Path, skill_slug: str, source_label: str, file_count: int) -> None:
    dev_dir = skill_dir / "augur" / "_dev"
    safe_mkdir(dev_dir)

    version_path = dev_dir / "version.yaml"
    changelog_path = dev_dir / "CHANGELOG.md"
    readme_path = dev_dir / "README.md"
    import_meta_path = dev_dir / "IMPORT.md"
    design_path = dev_dir / "design.md"
    todos_path = dev_dir / "todos.md"

    warning_todo = ""
    if file_count == 0:
        warning_todo = "- [ ] ⚠️ No code files imported. Implement backend logic.\n"

    if not version_path.exists():
        version_path.write_text(
            textwrap.dedent(f"""\
                skill: {skill_slug}
                version: 0.1.0
                updated: '{datetime.now().strftime('%Y-%m-%d')}'
                """),
            encoding="utf-8",
        )

    if not changelog_path.exists():
        changelog_path.write_text(
            textwrap.dedent(f"""\
                # Changelog

                ## [0.1.0] - {datetime.now().strftime('%Y-%m-%d')}

                - Imported skill into Augur
                """),
            encoding="utf-8",
        )

    if not readme_path.exists():
        readme_path.write_text(
            textwrap.dedent(f"""\
                # {skill_slug}

                Development metadata for this skill (versions, changelog, import provenance).

                - Generated README (user-facing): `../README.md`
                - Core orchestration: `../SKILL.md`
                - Full imported SKILL: `../references/imported-full-skill.md`
                """),
            encoding="utf-8",
        )

    if not design_path.exists():
        design_path.write_text(
            textwrap.dedent(f"""\
                # {skill_slug} Design

                ## Goal
                Describe the user problem this skill solves.

                ## Inputs / Outputs
                - Inputs:
                  - (Describe triggers / commands and expected inputs)
                - Outputs:
                  - (Files created/updated in skill data directory)

                ## Key Decisions
                - (Architecture decisions, constraints, tradeoffs)
                """),
            encoding="utf-8",
        )

    if not todos_path.exists():
        todos_path.write_text(
            textwrap.dedent(f"""\
                # TODOs

                {warning_todo}- [ ] Add missing modules/references
                - [ ] Add tests (if applicable)
                - [ ] Validate storage schema and data-template
                - [ ] Improve prompt examples / triggers in SKILL.md
                """),
            encoding="utf-8",
        )

    import_meta_path.write_text(
        textwrap.dedent(f"""\
            # Import Metadata

            - Imported At: {utc_now_iso()}
            - Source: {source_label}
            - Generated By: src/lib/scripts/skill_porter.py
            """),
        encoding="utf-8",
    )


def ensure_data_template(skill_dir: Path, tree_lines: list[str]) -> dict[str, Any]:
    data_template_dir = skill_dir / "data-template"
    safe_mkdir(data_template_dir)

    dirs, files = parse_storage_paths(tree_lines)

    for d in dirs:
        if str(d) in (".", ""):
            continue
        safe_mkdir(data_template_dir / d)

    for f in files:
        if str(f) in (".", ""):
            continue
        out = data_template_dir / f
        safe_mkdir(out.parent)
        if not out.exists():
            out.write_text("", encoding="utf-8")

    return {
        "data_template_path": str(data_template_dir),
        "dirs": [str(d) for d in dirs if str(d) not in (".", "")],
        "files": [str(f) for f in files if str(f) not in (".", "")],
    }


def ensure_user_data_scaffold(skill_slug: str, tree_lines: list[str]) -> dict[str, Any]:
    from src.config.paths import get_skill_data_dir  # type: ignore

    base = get_skill_data_dir(skill_slug)
    safe_mkdir(base)

    dirs, files = parse_storage_paths(tree_lines)
    for d in dirs:
        if str(d) in (".", ""):
            continue
        safe_mkdir(base / d)

    for f in files:
        if str(f) in (".", ""):
            continue
        out = base / f
        safe_mkdir(out.parent)
        if not out.exists():
            out.write_text("", encoding="utf-8")

    return {
        "data_dir": str(base),
        "dirs": [str(d) for d in dirs if str(d) not in (".", "")],
        "files": [str(f) for f in files if str(f) not in (".", "")],
    }


def move_source_readme_to_references(skill_dir: Path) -> None:
    readme = skill_dir / "README.md"
    if not readme.exists():
        return
    refs = skill_dir / "references"
    safe_mkdir(refs)
    target = refs / "source-readme.md"
    # Avoid overwriting.
    if target.exists():
        target = refs / f"source-readme-{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    shutil.move(str(readme), str(target))


def write_imported_full_skill(skill_dir: Path, original_skill: str) -> None:
    refs = skill_dir / "references"
    safe_mkdir(refs)
    out = refs / "imported-full-skill.md"
    out.write_text(original_skill, encoding="utf-8")


def generate_readme(skill_slug: str) -> None:
    script = REPO_ROOT / "src/lib" / "scripts" / "generate_skill_readmes.py"
    result = run([sys.executable, str(script), "--skill", skill_slug], cwd=REPO_ROOT)
    if result.returncode != 0:
        raise RuntimeError(f"README generation failed: {result.stderr.strip() or result.stdout.strip()}")


def backup_existing_skill(dest_dir: Path) -> Path:
    backup_root = PACKAGES_DIR / ".skill-import-backups"
    safe_mkdir(backup_root)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = backup_root / f"{dest_dir.name}_{ts}"
    shutil.move(str(dest_dir), str(backup_path))
    return backup_path


def resolve_conflict_slug(base_slug: str) -> str:
    if not (PACKAGES_DIR / base_slug).exists():
        return base_slug
    for i in range(2, 100):
        candidate = f"{base_slug}-v{i}"
        if not (PACKAGES_DIR / candidate).exists():
            return candidate
    raise RuntimeError("Unable to find an available versioned slug")


def build_analyze_plan(ctx: SourceContext) -> dict[str, Any]:
    proposed_slug, title, description = compute_dest_slug(ctx)
    dest_dir = PACKAGES_DIR / proposed_slug
    conflict = dest_dir.exists()

    raw_skill = ctx.skill_md.read_text(encoding="utf-8")
    trimmed, did_trim, original_lines = trim_skill_markdown(raw_skill, proposed_slug)
    storage_tree = extract_storage_tree(raw_skill)
    dirs, files = parse_storage_paths(storage_tree)

    candidates = [p.relative_to(ctx.skill_root).as_posix() for p in iter_copy_candidates(ctx.skill_root)]

    return {
        "source": {
            "kind": ctx.kind,
            "label": ctx.source_label,
            "skill_md": str(ctx.skill_md),
            "skill_root": str(ctx.skill_root),
        },
        "skill": {
            "slug": proposed_slug,
            "title": title,
            "description": description,
        },
        "conflict": {
            "exists": conflict,
            "dest_dir": str(dest_dir),
        },
        "skill_md": {
            "original_line_count": original_lines,
            "will_trim": did_trim,
        },
        "copy": {
            "file_count": len(candidates),
            "paths": candidates[:250],  # keep response bounded
            "paths_truncated": len(candidates) > 250,
        },
        "data_scaffold": {
            "dirs": [str(d) for d in dirs if str(d) not in (".", "")],
            "files": [str(f) for f in files if str(f) not in (".", "")],
        },
        "warnings": [],
    }


def apply_import(
    ctx: SourceContext,
    on_conflict: str,
    override_slug: str | None,
) -> dict[str, Any]:
    proposed_slug, title, _ = compute_dest_slug(ctx)

    if override_slug:
        override_slug = slugify(override_slug)
        if not is_kebab_case(override_slug):
            raise RuntimeError("Override slug must be kebab-case")
        dest_slug = override_slug
    else:
        dest_slug = proposed_slug

    dest_dir = PACKAGES_DIR / dest_slug
    backup_path = None

    if dest_dir.exists():
        if on_conflict == "block":
            raise RuntimeError(f"Skill already exists: {dest_slug}")
        if on_conflict == "overwrite":
            backup_path = str(backup_existing_skill(dest_dir))
        elif on_conflict == "versioned":
            dest_slug = resolve_conflict_slug(dest_slug)
            dest_dir = PACKAGES_DIR / dest_slug
        elif on_conflict == "new_slug":
            if not override_slug:
                raise RuntimeError("Conflict strategy 'new_slug' requires --slug")
            if dest_dir.exists():
                raise RuntimeError(f"Target slug already exists: {dest_slug}")
        else:
            raise RuntimeError(f"Unknown conflict strategy: {on_conflict}")

    safe_mkdir(dest_dir)

    # Copy all relevant files from source skill_root.
    copied = 0
    for src in iter_copy_candidates(ctx.skill_root):
        rel = src.relative_to(ctx.skill_root)
        dest = dest_dir / rel
        safe_mkdir(dest.parent)
        shutil.copy2(src, dest)
        copied += 1

    # Preserve any source README.md before generating our own.
    move_source_readme_to_references(dest_dir)

    # Ensure references dir exists for full SKILL content.
    original_skill = ctx.skill_md.read_text(encoding="utf-8")
    write_imported_full_skill(dest_dir, original_skill)

    # Auto-trim/normalize SKILL.md.
    trimmed, _, original_lines = trim_skill_markdown(original_skill, dest_slug)
    (dest_dir / "SKILL.md").write_text(trimmed, encoding="utf-8")

    # Data scaffolding.
    storage_tree = extract_storage_tree(original_skill)
    data_scaffold = ensure_user_data_scaffold(dest_slug, storage_tree)
    data_template = ensure_data_template(dest_dir, storage_tree)

    # Dev metadata.
    ensure_dev_metadata(dest_dir, dest_slug, ctx.source_label, copied)

    # Generated README (help).
    generate_readme(dest_slug)

    return {
        "status": "success",
        "skill": {
            "slug": dest_slug,
            "title": title,
            "package_dir": str(dest_dir),
        },
        "backup": backup_path,
        "copied_files": copied,
        "skill_md_original_lines": original_lines,
        "data_scaffold": data_scaffold,
        "data_template": data_template,
        "notes": [
            "Skill imported into plugins/",
            "README generated from SKILL.md (Help uses README.md)",
            "User data scaffold created in augur (separate from shareable code)",
        ],
    }


def export_skill(skill_slug: str, out_path: Path) -> dict[str, Any]:
    skill_dir = PACKAGES_DIR / skill_slug
    if not skill_dir.exists():
        raise RuntimeError(f"Skill not found: {skill_slug}")

    safe_mkdir(out_path.parent)

    def include_path(p: Path) -> bool:
        if p.is_dir():
            return False
        if any(part in IGNORED_DIRS for part in p.parts):
            return False
        if should_ignore_path(p):
            return False
        return True

    with zipfile.ZipFile(out_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for p in skill_dir.rglob("*"):
            if not include_path(p):
                continue
            rel = p.relative_to(skill_dir)
            zf.write(p, arcname=str(Path(skill_slug) / rel))

    return {
        "status": "success",
        "skill": skill_slug,
        "zip": str(out_path),
    }
