from __future__ import annotations

import hashlib
import json
import math
import os
import re
import tempfile
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

import yaml

from src.lib.brain_registry import get_registry
from src.lib.brain_registry_models import BrainType

INVENTORY_RELATIVE_PATH = Path("config") / "inventory" / "ai-artifacts.json"
INVENTORY_SCHEMA_VERSION = 1
_MAX_DIGEST_BYTES = 1024 * 1024
_GENERATED_MARKERS = (
    "AUTO-GENERATED FILE",
    "generated_projection: true",
    "Generated by Augur",
    "DO NOT EDIT DIRECTLY",
)
_SKIP_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".next",
    ".venv",
    "__pycache__",
    "node_modules",
    "dist",
    "build",
}
_PROMPT_METADATA_KEYS = {
    "description",
    "id",
    "label",
    "name",
    "prompt",
    "title",
}
PROBLEM_LABELS: dict[str, str] = {
    "permission_denied": "Permission denied",
    "unreadable": "Unreadable",
    "unknown_source": "Unknown source",
    "low_confidence": "Low confidence",
    "duplicate": "Duplicate",
    "stale_generated": "Stale generated",
    "conflicting_instruction": "Conflicting instruction",
    "missing_mcp_config": "Missing MCP config",
}
PROBLEM_SEVERITY: dict[str, str] = {
    "permission_denied": "danger",
    "unreadable": "danger",
    "unknown_source": "warning",
    "low_confidence": "warning",
    "duplicate": "warning",
    "stale_generated": "warning",
    "conflicting_instruction": "warning",
    "missing_mcp_config": "info",
}
_AI_CLIENT_ARTIFACT_TYPES = {"agent-profile", "instruction", "prompt", "skill"}
_CLIENT_DIRS = {".codex", ".claude", ".gemini", ".cursor", ".vscode", ".github", ".opencode"}
_ROOT_SOURCE_FILES = {
    "AGENTS.md",
    "CLAUDE.md",
    "CODEX.md",
    "GEMINI.md",
    "README.md",
    "llms.txt",
    "llms-full.txt",
    ".mcp.json",
}
_SOURCE_PREFIXES = ("project-brain/", "plugins/", "docs/", "skills/")


@dataclass(frozen=True)
class AiArtifactRecord:
    id: str
    project_brain_id: str
    project_root: str
    artifact_type: str
    client: str
    vendor: str
    source_path: str
    relative_path: str
    title: str
    classification: str
    confidence: float
    warnings: list[str]
    discovered_at: str
    freshness: str
    provenance: dict[str, str]


@dataclass(frozen=True)
class AiArtifactInventory:
    schema_version: int
    project_brain_id: str
    project_root: str
    generated_at: str
    artifacts: list[AiArtifactRecord]
    warnings: list[str]


def scan_ai_artifacts(
    project_root: Path,
    project_brain_id: str,
    discovered_at: str | None = None,
) -> AiArtifactInventory:
    root = project_root.expanduser().resolve()
    generated_at = discovered_at or datetime.now(timezone.utc).isoformat()
    records: list[AiArtifactRecord] = []
    warnings: list[str] = []
    seen: set[Path] = set()

    candidates = _candidate_paths(root, warnings)
    for artifact_type, paths in candidates.items():
        for path in paths:
            rel = _relative_path(path, root)
            try:
                resolved = path.resolve()
            except OSError as exc:
                warnings.append(f"{rel}: {exc.strerror or exc.__class__.__name__}")
                continue
            if not _is_relative_to(resolved, root):
                warnings.append(f"{rel}: resolved target outside project_root")
                continue
            if resolved in seen:
                continue
            seen.add(resolved)
            try:
                records.append(
                    _record_for_path(
                        path=resolved,
                        project_root=root,
                        project_brain_id=project_brain_id,
                        artifact_type=artifact_type,
                        discovered_at=generated_at,
                    )
                )
            except OSError as exc:
                warnings.append(f"{rel}: {exc.strerror or exc.__class__.__name__}")

    records.sort(key=lambda item: (item.artifact_type, item.relative_path))
    return AiArtifactInventory(
        schema_version=INVENTORY_SCHEMA_VERSION,
        project_brain_id=project_brain_id,
        project_root=str(root),
        generated_at=generated_at,
        artifacts=records,
        warnings=warnings,
    )


def write_ai_artifact_inventory(inventory: AiArtifactInventory, brain_root: Path) -> Path:
    target = brain_root / INVENTORY_RELATIVE_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    payload = _inventory_to_dict(inventory)
    fd, tmp_name = tempfile.mkstemp(prefix=".ai-artifacts-", suffix=".json", dir=target.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2, sort_keys=True)
            handle.write("\n")
        Path(tmp_name).replace(target)
    finally:
        tmp_path = Path(tmp_name)
        if tmp_path.exists():
            tmp_path.unlink()
    return target


def load_ai_artifact_inventory(brain_root: Path) -> AiArtifactInventory | None:
    path = brain_root / INVENTORY_RELATIVE_PATH
    if not path.is_file():
        return None
    payload = json.loads(path.read_text(encoding="utf-8"))
    records = [AiArtifactRecord(**record) for record in payload.get("artifacts", [])]
    return AiArtifactInventory(
        schema_version=int(payload.get("schema_version", INVENTORY_SCHEMA_VERSION)),
        project_brain_id=str(payload.get("project_brain_id") or ""),
        project_root=str(payload.get("project_root") or ""),
        generated_at=str(payload.get("generated_at") or ""),
        artifacts=records,
        warnings=[str(item) for item in payload.get("warnings", [])],
    )


def inventory_browse_entries_for_category(category: str) -> list[dict[str, object]]:
    mapping = {
        "skills": {"skill"},
        "agent-profiles": {"agent-profile"},
        "system-metadata": {"instruction", "mcp-config", "project-doc", "prompt"},
        "mcp-servers": {"mcp-config"},
    }
    wanted = mapping.get(category)
    if not wanted:
        return []
    entries: list[dict[str, object]] = []
    for inventory in load_registered_project_inventories():
        for record in inventory.artifacts:
            if record.artifact_type not in wanted:
                continue
            if category == "skills" and record.classification == "generated":
                # Generated client artifacts are projections of canonical Augur
                # surfaces (commands/skills); they must not surface as standalone
                # skill cards (spec workstream 2: dedupe autosync export copies).
                continue
            entries.append(_record_to_browse_entry(record, category, inventory.artifacts))
    return entries


def derive_ai_artifact_problem_metadata(
    record: AiArtifactRecord,
    all_records: Iterable[AiArtifactRecord],
) -> dict[str, str]:
    records = list(all_records)
    evidence = _artifact_problem_evidence(record, records)
    if not evidence:
        return {}
    tags = [str(item["id"]) for item in evidence]
    return {
        "problem_tags": ",".join(tags),
        "problem_count": str(len(tags)),
        "problem_summary": PROBLEM_LABELS.get(tags[0], _humanize_problem_id(tags[0])),
        "problem_evidence": json.dumps(evidence, sort_keys=True, separators=(",", ":")),
    }


def load_registered_project_inventories() -> list[AiArtifactInventory]:
    inventories: list[AiArtifactInventory] = []
    registry = get_registry()
    for brain in registry.brains.values():
        if brain.type is not BrainType.PROJECT:
            continue
        inventory = load_ai_artifact_inventory(Path(str(brain.data_root)).expanduser())
        if inventory is not None:
            inventories.append(inventory)
    return inventories


def _candidate_paths(root: Path, warnings: list[str]) -> dict[str, list[Path]]:
    candidates: dict[str, list[Path]] = {
        "instruction": _existing(
            root,
            [
                "AGENTS.md",
                "CLAUDE.md",
                "CODEX.md",
                "GEMINI.md",
                ".cursor/rules/augur.mdc",
                ".github/copilot-instructions.md",
            ],
        ),
        "mcp-config": _existing(
            root,
            [
                ".mcp.json",
                ".claude/mcp.json",
                ".cursor/mcp.json",
                ".codex/config.toml",
                ".gemini/settings.json",
                ".vscode/mcp.json",
            ],
        ),
        "project-doc": _existing(
            root,
            [
                "README.md",
                "llms.txt",
                "llms-full.txt",
            ],
        ),
        "skill": [],
        "agent-profile": [],
        "prompt": [],
    }
    candidates["instruction"].extend(_glob(root, ".cursor/rules/*", warnings))
    candidates["instruction"].extend(_glob(root, ".github/instructions/*", warnings))
    for rel in (".codex/skills", ".claude/skills", ".gemini/skills", ".opencode/skills", "skills"):
        candidates["skill"].extend(_glob(root, f"{rel}/*/SKILL.md", warnings))
    for rel in (
        ".codex/agents",
        ".claude/agents",
        ".cursor/agents",
        ".github/agents",
        "plugins/agents",
    ):
        candidates["agent-profile"].extend(
            # README.md documents the profile format; it is not a profile.
            path
            for path in _glob(root, f"{rel}/*.md", warnings)
            if path.name != "README.md"
        )
    for rel in (".codex/prompts", ".claude/prompts", ".gemini/prompts", ".github/prompts", "prompts"):
        candidates["prompt"].extend(_prompt_candidates(root, rel, warnings))
    candidates["project-doc"].extend(_glob(root, "docs/agent-topics/*.md", warnings))
    return candidates


def _existing(root: Path, relatives: Iterable[str]) -> list[Path]:
    return [root / rel for rel in relatives if (root / rel).is_file()]


def _glob(root: Path, pattern: str, warnings: list[str]) -> list[Path]:
    try:
        return [
            path
            for path in sorted(root.glob(pattern))
            if path.is_file() and not any(part in _SKIP_DIRS for part in _relative_parts(path, root))
        ]
    except OSError as exc:
        warnings.append(f"{pattern}: {_os_error_message(exc)}")
        return []


def _prompt_candidates(root: Path, rel: str, warnings: list[str]) -> list[Path]:
    candidates: list[Path] = []
    for path in _glob(root, f"{rel}/*.md", warnings):
        try:
            if _is_prompt_artifact(path, _read_text_sample(path)):
                candidates.append(path)
        except OSError as exc:
            warnings.append(f"{_relative_path(path, root)}: {_os_error_message(exc)}")
    return candidates


def _is_prompt_artifact(path: Path, text: str) -> bool:
    if path.name.endswith(".prompt.md"):
        return True
    metadata, invalid = _frontmatter_metadata(text)
    if invalid:
        return True
    return bool(metadata and _PROMPT_METADATA_KEYS.intersection(metadata))


def _record_for_path(
    *,
    path: Path,
    project_root: Path,
    project_brain_id: str,
    artifact_type: str,
    discovered_at: str,
) -> AiArtifactRecord:
    rel = _relative_path(path, project_root)
    text = _read_text_sample(path)
    classification, confidence, warnings = _classify(path, rel, text)
    title = _title_for(path, text)
    artifact_id = hashlib.sha256(f"{project_brain_id}:{artifact_type}:{rel}".encode("utf-8")).hexdigest()[:16]
    return AiArtifactRecord(
        id=f"ai-artifact:{project_brain_id}:{artifact_id}",
        project_brain_id=project_brain_id,
        project_root=str(project_root),
        artifact_type=artifact_type,
        client=_client_for(rel),
        vendor=_vendor_for(rel),
        source_path=str(path),
        relative_path=rel,
        title=title,
        classification=classification,
        confidence=confidence,
        warnings=warnings,
        discovered_at=discovered_at,
        freshness=_freshness(path),
        provenance={
            "scanner": "ai-artifact-inventory",
            "source_path": str(path),
            "relative_path": rel,
        },
    )


def _classify(path: Path, rel: str, text: str) -> tuple[str, float, list[str]]:
    metadata_warnings = _frontmatter_warnings(path, text)
    if any(marker in text for marker in _GENERATED_MARKERS):
        return "generated", 0.95, metadata_warnings
    parts = rel.split("/")
    if any(part in _CLIENT_DIRS for part in parts):
        # A copy living under an AI-client export dir is an autosync projection.
        return "generated", 0.9, metadata_warnings
    if rel in _ROOT_SOURCE_FILES or rel.startswith(_SOURCE_PREFIXES):
        return "source", 0.85, metadata_warnings
    return "unknown", 0.4, ["unknown_source", *metadata_warnings]


def _frontmatter_warnings(path: Path, text: str) -> list[str]:
    if path.suffix not in {".md", ".mdc"} or not text.startswith("---"):
        return []

    _metadata, invalid = _frontmatter_metadata(text)
    if invalid:
        return ["invalid_metadata"]
    return []


def _frontmatter_metadata(text: str) -> tuple[dict[str, object] | None, bool]:
    if not text.startswith("---"):
        return None, False

    lines = text.splitlines()
    end_index = next((idx for idx, line in enumerate(lines[1:], start=1) if line == "---"), None)
    if end_index is None:
        return None, True

    raw_frontmatter = "\n".join(lines[1:end_index])
    try:
        parsed = yaml.safe_load(raw_frontmatter)
    except yaml.YAMLError:
        return None, True
    if not isinstance(parsed, dict):
        return None, True
    return parsed, False


def _os_error_message(exc: OSError) -> str:
    return exc.strerror or str(exc) or exc.__class__.__name__


def _read_text_sample(path: Path) -> str:
    with path.open("r", encoding="utf-8", errors="ignore") as handle:
        return handle.read(16384)


def _title_for(path: Path, text: str) -> str:
    frontmatter_name = re.search(r"(?m)^(?:label|name|title):\s*(.+?)\s*$", text)
    if frontmatter_name:
        return frontmatter_name.group(1).strip().strip('"')
    return path.stem.replace("-", " ").replace("_", " ").title()


def _freshness(path: Path) -> str:
    stat = path.stat()
    if stat.st_size > _MAX_DIGEST_BYTES:
        return f"mtime:{stat.st_mtime_ns}"
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    return f"sha256:{digest}"


def _relative_path(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def _relative_parts(path: Path, root: Path) -> tuple[str, ...]:
    try:
        return path.relative_to(root).parts
    except ValueError:
        return path.parts


def _is_relative_to(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
    except ValueError:
        return False
    return True


def _client_for(rel: str) -> str:
    parts = rel.split("/")
    if ".codex" in parts:
        return "codex"
    if ".claude" in parts:
        return "claude"
    if ".gemini" in parts:
        return "gemini"
    if ".cursor" in parts:
        return "cursor"
    if ".vscode" in parts:
        return "vscode"
    if ".github" in parts:
        return "copilot"
    if rel.startswith("plugins/agents/"):
        return "augur"
    return "project"


def _vendor_for(rel: str) -> str:
    client = _client_for(rel)
    if client == "copilot":
        return "github"
    if client == "project":
        return "project"
    return client


def _artifact_problem_evidence(
    record: AiArtifactRecord,
    records: list[AiArtifactRecord],
) -> list[dict[str, object]]:
    problems: list[dict[str, object]] = []
    warning_ids = {_normalize_problem_id(warning) for warning in record.warnings}

    for problem_id in (
        "permission_denied",
        "unreadable",
        "unknown_source",
        "stale_generated",
    ):
        if problem_id in warning_ids:
            _append_problem(problems, record, problem_id, f"Scanner warning: {problem_id}")

    confidence = _coerce_confidence(record.confidence)
    if confidence is not None and confidence < 0.5:
        _append_problem(
            problems,
            record,
            "low_confidence",
            f"Classification confidence is {confidence:.2f}.",
        )

    duplicates = _duplicate_artifacts(record, records)
    if duplicates:
        _append_problem(
            problems,
            record,
            "duplicate",
            "Another artifact has the same client, artifact type, and title.",
            related_paths=[item.relative_path for item in duplicates],
        )

    conflicts = _conflicting_instruction_artifacts(record, records)
    if record.artifact_type == "instruction" and conflicts:
        _append_problem(
            problems,
            record,
            "conflicting_instruction",
            "Multiple instruction artifacts target the same client.",
            related_paths=[item.relative_path for item in conflicts],
        )

    if (
        _project_has_client_artifacts(records)
        and not _project_has_mcp_config(records)
        and record.artifact_type in _AI_CLIENT_ARTIFACT_TYPES
    ):
        _append_problem(
            problems,
            record,
            "missing_mcp_config",
            "AI-client artifacts were found, but no MCP/config artifact was detected in this project inventory.",
        )

    return problems


def _append_problem(
    problems: list[dict[str, object]],
    record: AiArtifactRecord,
    problem_id: str,
    reason: str,
    *,
    related_paths: Iterable[str] | None = None,
) -> None:
    if any(item.get("id") == problem_id for item in problems):
        return
    evidence: dict[str, object] = {
        "id": problem_id,
        "severity": PROBLEM_SEVERITY.get(problem_id, "info"),
        "reason": reason,
        "source_path": record.source_path,
    }
    if related_paths:
        evidence["related_paths"] = sorted({path for path in related_paths if path})
    problems.append(evidence)


def _normalize_problem_id(raw: str) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "_", raw.strip().lower()).strip("_")
    for problem_id in PROBLEM_LABELS:
        if normalized == problem_id or problem_id in normalized:
            return problem_id
    if "permission" in normalized and "denied" in normalized:
        return "permission_denied"
    return normalized


def _duplicate_artifacts(
    record: AiArtifactRecord,
    records: list[AiArtifactRecord],
) -> list[AiArtifactRecord]:
    duplicates = [
        item
        for item in records
        if item.id != record.id
        and item.client == record.client
        and item.artifact_type == record.artifact_type
        and item.title == record.title
    ]
    return sorted(duplicates, key=lambda item: (item.relative_path, item.id))


def _conflicting_instruction_artifacts(
    record: AiArtifactRecord,
    records: list[AiArtifactRecord],
) -> list[AiArtifactRecord]:
    if record.artifact_type != "instruction":
        return []
    return _duplicate_artifacts(record, records)


def _project_has_client_artifacts(records: list[AiArtifactRecord]) -> bool:
    return any(item.artifact_type in _AI_CLIENT_ARTIFACT_TYPES for item in records)


def _project_has_mcp_config(records: list[AiArtifactRecord]) -> bool:
    return any(item.artifact_type == "mcp-config" for item in records)


def _humanize_problem_id(problem_id: str) -> str:
    return problem_id.replace("_", " ").capitalize()


def _coerce_confidence(value: object) -> float | None:
    if value is None:
        return None
    try:
        confidence = float(value)
    except (TypeError, ValueError):
        return None
    if not math.isfinite(confidence):
        return None
    return confidence


def _format_confidence(value: object) -> str:
    confidence = _coerce_confidence(value)
    if confidence is not None:
        return f"{confidence:.2f}"
    if value is None or isinstance(value, float):
        return ""
    return str(value)


def _inventory_to_dict(inventory: AiArtifactInventory) -> dict[str, object]:
    return {
        "schema_version": inventory.schema_version,
        "project_brain_id": inventory.project_brain_id,
        "project_root": inventory.project_root,
        "generated_at": inventory.generated_at,
        "artifacts": [asdict(record) for record in inventory.artifacts],
        "warnings": inventory.warnings,
    }


def _record_to_browse_entry(
    record: AiArtifactRecord,
    category: str,
    all_records: Iterable[AiArtifactRecord],
) -> dict[str, object]:
    problem_metadata = derive_ai_artifact_problem_metadata(record, all_records)
    metadata = {
        "brain_id": record.project_brain_id,
        "project_root": record.project_root,
        "artifact_type": record.artifact_type,
        "client": record.client,
        "vendor": record.vendor,
        "classification": record.classification,
        "confidence": _format_confidence(record.confidence),
        "warnings": ",".join(record.warnings),
        "relative_path": record.relative_path,
        "inventory_source": "ai-artifact-inventory",
    }
    metadata.update(problem_metadata)
    problem_tags = [item.strip() for item in problem_metadata.get("problem_tags", "").split(",") if item.strip()]
    title = record.title or Path(record.relative_path).name
    return {
        "id": record.id,
        "name": record.id,
        "title": title,
        "description": (f"{record.client} {record.artifact_type} artifact in " f"{Path(record.project_root).name}"),
        "hub": "system" if category != "skills" else "external",
        "type": record.artifact_type,
        "source_path": record.source_path,
        "tags": [record.client, record.artifact_type, record.classification, *problem_tags],
        "brain_id": record.project_brain_id,
        "project_root": record.project_root,
        "artifact_type": record.artifact_type,
        "client": record.client,
        "vendor": record.vendor,
        "classification": record.classification,
        "confidence": _format_confidence(record.confidence),
        "warnings": ",".join(record.warnings),
        "relative_path": record.relative_path,
        "inventory_source": "ai-artifact-inventory",
        "metadata": metadata,
        "ownership": "external" if record.classification != "source" else "augur",
        "source": record.client,
    }
