from __future__ import annotations

from pathlib import Path

from src.lib.brain_manifest import BrainManifest, write_brain_manifest
from src.lib.brain_registry_models import Brain


def mount_dir_for_brain(brain: Brain) -> Path:
    """Return where the brain's manifest mount lives.

    ``brain.data_root`` is a cross-platform ``PurePath`` (ADR-754 — a brain may
    describe a root on another machine/OS). Convert to a concrete ``Path`` here,
    the single boundary where filesystem ops operate on a real path. Callers
    must still gate on local existence before mounting a non-local brain.
    """
    return Path(brain.data_root)


def ensure_mount(brain: Brain) -> Path:
    """Create or refresh the brain's root BRAIN.yaml manifest.

    ``BrainManifest.from_brain`` serializes registry-absolute root/
    attached_project paths, but ``write_brain_manifest`` preserves the committed
    manifest's path style when the existing strings resolve to the same location
    (``_preserve_manifest_path_style``), so the portable relative form
    (`root: .`) is no longer clobbered with machine-specific churn on rewrite.

    Per-client harness files (CLAUDE.md, AGENTS.md, GEMINI.md, mcp.json) are
    generated by sync adapters.
    """
    mount = mount_dir_for_brain(brain)
    attached_project = Path(brain.git.host_repo) if brain.git.host_repo else None
    write_brain_manifest(
        mount,
        BrainManifest.from_brain(brain, attached_project=attached_project),
    )
    return mount
