#!/usr/bin/env python3
"""
Validate Skill Directory Structure (ADR-430)

Pre-commit hook that blocks commits containing banned skill structure patterns.
Catches deprecated metadata files, auto-generated artifacts, stale directories,
user data files, and garbage files before they enter version control.

Usage:
    python3 validate_skill_structure.py file1 file2 ...  # Check specific files
    python3 validate_skill_structure.py                  # Check staged files
"""

import re
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent

# Patterns that BLOCK commits (exit 1)
BANNED_PATTERNS = [
    # Metadata files replaced by plugin system
    (
        r"project-brain/capabilities/skills/[^/]+/\.config$",
        "Use plugin enable/disable instead of .config (ADR-430)",
    ),
    (
        r"project-brain/capabilities/skills/[^/]+/augur/version\.yaml$",
        "Use plugin.json version instead of version.yaml (ADR-430)",
    ),
    (
        r"project-brain/capabilities/skills/[^/]+/requirements\.txt$",
        "Use plugin-level requirements (ADR-430)",
    ),
    # Auto-generated files
    (
        r"project-brain/capabilities/skills/[^/]+/augur/README\.md$",
        "Auto-generated by mount-plugins, don't commit (ADR-430)",
    ),
    (
        r"project-brain/capabilities/skills/[^/]+/augur/api/tsconfig\.json$",
        "Auto-generated by mount-plugins (ADR-430)",
    ),
    (
        r"project-brain/capabilities/skills/[^/]+/augur/dashboard/tsconfig\.json$",
        "Auto-generated by mount-plugins (ADR-430)",
    ),
    # Stale/deprecated directories
    # SUPERSEDED by ADR-479: augur/data/ is now allowed for runtime config.
    # Seeds moved to assets/seeds/. Schema enforcement handles this via BANNED_AUGUR_DIRS.
    # (r"project-brain/capabilities/skills/[^/]+/augur/data/", "augur/data/ is deprecated, use assets/seeds/ (ADR-430)"),
    (
        r"project-brain/capabilities/skills/[^/]+/assets/prompts/",
        "assets/prompts/ consolidated into assets/seeds/prompts/ (ADR-430)",
    ),
    (
        r"project-brain/capabilities/skills/[^/]+/assets/seed-data/",
        "Renamed to assets/seeds/ (ADR-430)",
    ),
    # User data files
    (
        r"project-brain/capabilities/skills/.*\.(xlsx|docx|m4a|mp3|mp4|wav|pptx)$",
        "User data files belong in vault, not git (ADR-430)",
    ),
    # Garbage
    (
        r"project-brain/capabilities/skills/.*\.DS_Store$",
        ".DS_Store should not be committed",
    ),
    (
        r"project-brain/capabilities/skills/.*__pycache__/",
        "__pycache__ should not be committed",
    ),
]

# Skill folder schema enforcement (ADR-479, agentskills.io standard)
ALLOWED_ROOT_DIRS = {
    "commands", "references", "scripts", "assets",
    "examples", "evals", "modules", "augur",
}

BANNED_ROOT_DIRS = {
    "docs", "data", "lib",
    ".augur-plugin", "node_modules", "__pycache__",
}

BANNED_AUGUR_DIRS = {
    "seed",  # moved to assets/seeds/
}

DASHBOARD_ALLOWED_EXTENSIONS = {
    ".tsx", ".ts", ".css", ".js", ".jsx",
}

DASHBOARD_EXCEPTIONS = {
    "tsconfig.json",
}

# Pattern to extract skill name from a project-brain/capabilities/skills/{name}/... path
SKILL_NAME_RE = re.compile(r"project-brain/capabilities/skills/([^/]+)/")


def check_banned_patterns(file_path: str) -> list[str]:
    """Check a file path against all banned patterns. Returns list of violations."""
    violations = []
    for pattern, message in BANNED_PATTERNS:
        if re.search(pattern, file_path):
            violations.append(message)
    return violations


def check_schema_compliance(file_path: str) -> list[str]:
    """Check file path against skill folder schema."""
    violations = []
    parts = Path(file_path).parts

    # Must be project-brain/capabilities/skills/{name}/...
    if (
        len(parts) < 5
        or parts[0] != "project-brain"
        or parts[1] != "capabilities"
        or parts[2] != "skills"
    ):
        return []

    skill_name = parts[3]

    if len(parts) >= 5:
        subdir = parts[4]
        # Check banned root dirs
        if subdir in BANNED_ROOT_DIRS and len(parts) > 4:
            violations.append(
                f"project-brain/capabilities/skills/{skill_name}/{subdir}/ is banned at skill root. "
                f"Use references/ (not docs/), augur/data/ (not data/), "
                f"scripts/ (not lib/)."
            )

    # Check banned augur subdirs
    if len(parts) >= 6 and parts[4] == "augur":
        augur_subdir = parts[5]
        if augur_subdir in BANNED_AUGUR_DIRS:
            violations.append(
                f"project-brain/capabilities/skills/{skill_name}/augur/{augur_subdir}/ is banned. "
                f"Use assets/seeds/ instead of augur/seed/."
            )

        # Dashboard extension check
        if augur_subdir == "dashboard" and len(parts) >= 7:
            filename = parts[-1]
            if Path(filename).suffix and Path(filename).suffix not in DASHBOARD_ALLOWED_EXTENSIONS:
                if filename not in DASHBOARD_EXCEPTIONS:
                    violations.append(
                        f"augur/dashboard/ allows only {', '.join(sorted(DASHBOARD_ALLOWED_EXTENSIONS))} files. "
                        f"Found: {filename}"
                    )

    return violations


def check_missing_skill_md(file_paths: list[str]) -> list[tuple[str, str]]:
    """Block touched skill directories that lack a required SKILL.md."""
    violations: list[tuple[str, str]] = []
    skill_names: set[str] = set()

    for fp in file_paths:
        m = SKILL_NAME_RE.search(fp)
        if m:
            skill_names.add(m.group(1))

    for name in sorted(skill_names):
        skill_md = PROJECT_ROOT / "project-brain" / "capabilities" / "skills" / name / "SKILL.md"
        if not skill_md.exists():
            violations.append((
                f"project-brain/capabilities/skills/{name}/SKILL.md",
                f"Skill '{name}' is missing required SKILL.md",
            ))

    return violations


def get_staged_files() -> list[str]:
    """Get staged file paths from git (relative to repo root)."""
    try:
        result = subprocess.run(
            ["git", "diff", "--cached", "--name-only", "--diff-filter=ACM"],
            capture_output=True,
            text=True,
            cwd=PROJECT_ROOT,
        )
        if result.returncode == 0:
            return [f for f in result.stdout.strip().split("\n") if f]
    except (subprocess.SubprocessError, FileNotFoundError):
        pass
    return []


def main() -> int:
    # Collect file paths
    if len(sys.argv) > 1:
        file_paths = sys.argv[1:]
    else:
        file_paths = get_staged_files()

    if not file_paths:
        return 0

    # Check for violations
    violations: list[tuple[str, str]] = []
    for fp in file_paths:
        for msg in check_banned_patterns(fp):
            violations.append((fp, msg))
        for msg in check_schema_compliance(fp):
            violations.append((fp, msg))

    # Check for missing SKILL.md (blocking)
    violations.extend(check_missing_skill_md(file_paths))

    # Print violations (blocking)
    if violations:
        print("\nBlocked by skill structure validation (ADR-430):")
        print("=" * 60)
        for fp, msg in violations:
            print(f"\n  {fp}")
            print(f"    {msg}")
        print(f"\n{len(violations)} violation(s) found. Commit blocked.")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
