/**
 * Build Scripts — Compile TypeScript build scripts to JavaScript using esbuild.
 *
 * This file is plain JS (.mjs) so it can bootstrap without any TS tooling.
 * All dashboard TS scripts are compiled to ESM .mjs files in scripts/dist/.
 *
 * Usage:
 *   node scripts/build-scripts.mjs
 *
 * Runs automatically via:
 *   - `npm install` (prepare hook)
 *   - `npm run dev` (start-dev.sh)
 *   - `npm run build` (prebuild hook)
 */

import esbuild from "esbuild";

const ENTRY_POINTS = [
  "scripts/setup-mcp.ts",
  "scripts/mount-plugins.ts",
  "scripts/generate-tab-registry.ts",
  "scripts/generate-block-registry.ts",
  "scripts/generate-page-manifest.ts",
  "scripts/generate-item-actions.ts",
  "scripts/validate-nav-alignment.ts",
  "scripts/validate-no-legacy-pages.ts",
  "scripts/debug-yaml.ts",
  "scripts/rebuild-plugins.ts",
  "scripts/ui/scaffold.ts",
];

await esbuild.build({
  entryPoints: ENTRY_POINTS,
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node20",
  outdir: "scripts/dist",
  outExtension: { ".js": ".mjs" },
  external: ["yaml", "js-yaml", "zod"],
  banner: { js: "// Auto-generated by build-scripts.mjs — do not edit" },
  logLevel: "warning",
});
