import fs from "fs/promises";
import path from "path";
import { notFound } from "next/navigation";
import {
  getSourcePrefix,
  resolveSkillInfo,
  stripAutoHeader,
} from "@/lib/server/skillsLookup";

const ADR270_PLACEHOLDER =
  "Generated by ADR-270 migration. Update from SKILL.md.";

function isPlaceholderReadme(markdown: string): boolean {
  return stripAutoHeader(markdown).includes(ADR270_PLACEHOLDER);
}

export async function loadSkillReadme(
  repoRoot: string,
  skill: string,
): Promise<{ sourcePath: string; markdown: string; canonicalId: string }> {
  const resolved = await resolveSkillInfo(skill);
  if (!resolved) {
    notFound();
  }

  const skillDir =
    resolved.absolutePath ??
    path.join(
      repoRoot,
      resolved.baseDir || "plugins",
      resolved.path,
    );

  const skillDirStat = await fs.stat(skillDir).catch(() => null);
  if (!skillDirStat?.isDirectory()) {
    notFound();
  }

  const baseSourcePrefix = getSourcePrefix(resolved);
  const candidates: Array<{
    path: string;
    source: string;
    allowPlaceholder?: boolean;
  }> = [];

  if (resolved.source === "skill-package") {
    candidates.push({
      path: path.join(skillDir, "skill-package", "SKILL.md"),
      source: `${baseSourcePrefix}/skill-package/SKILL.md`,
      allowPlaceholder: true,
    });
  }

  candidates.push(
    {
      path: path.join(skillDir, "augur", "README.md"),
      source: `${baseSourcePrefix}/augur/README.md`,
    },
    {
      path: path.join(skillDir, "SKILL.md"),
      source: `${baseSourcePrefix}/SKILL.md`,
      allowPlaceholder: true,
    },
    {
      path: path.join(skillDir, "README.md"),
      source: `${baseSourcePrefix}/README.md`,
      allowPlaceholder: true,
    },
  );

  const candidateReads = await Promise.all(
    candidates.map(async (candidate) => {
      try {
        const markdown = await fs.readFile(candidate.path, "utf8");
        if (!candidate.allowPlaceholder && isPlaceholderReadme(markdown)) {
          return null;
        }
        return {
          sourcePath: candidate.source,
          markdown,
          canonicalId: resolved.canonicalId,
        };
      } catch {
        return null;
      }
    }),
  );
  const match = candidateReads.find(Boolean);
  if (match) return match;

  notFound();
}
