/**
 * Static icon map for tree-shakeable dynamic icon resolution.
 *
 * Replaces `import * as LucideIcons` (which bundles ~1500 icons)
 * with an explicit map of ~95 icons actually used in the app.
 * Unknown icon names fall back to FileText.
 *
 * To add a new icon: import it from lucide-react and add it to ICON_MAP.
 */

import {
  // Hub icons (from assembled-hubs.json)
  Activity,
  Apple,
  Archive,
  ArrowRightLeft,
  BarChart3,
  Bell,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Bookmark,
  Brain,
  BrainCircuit,
  Briefcase,
  BriefcaseBusiness,
  Building2,
  ChefHat,
  Command,
  Compass,
  Copy,
  FileCheck,
  FileCheck2,
  FileCode2,
  FileText,
  Files,
  Film,
  Folder,
  FolderGit2,
  FolderOpen,
  FolderTree,
  Gauge,
  Hammer,
  HardDrive,
  Heart,
  HeartPulse,
  House,
  LayoutDashboard,
  Library,
  Link,
  Megaphone,
  Mic,
  Package,
  Palette,
  PiggyBank,
  Power,
  Presentation,
  RefreshCw,
  Scale,
  Search,
  Settings2,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Bug,
  Target,
  Terminal,
  TestTube2,
  Trash2,
  TrendingUp,
  Users,
  Wallet,
  Watch,
  Workflow,
  Zap,
  // Common UI icons used across dashboard components
  AlertCircle,
  AlertTriangle,
  AreaChart,
  ArrowRight,
  Box,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  ClipboardCheck,
  Clock,
  Code,
  Database,
  DollarSign,
  Download,
  Eye,
  Globe,
  Grid,
  Grid2x2Plus,
  Home,
  Image,
  Info,
  Layers,
  Lightbulb,
  List,
  Loader2,
  Lock,
  Menu,
  MessageSquare,
  MoreHorizontal,
  MoreVertical,
  Paperclip,
  Pencil,
  PieChart,
  Play,
  Plus,
  Puzzle,
  Send,
  Server,
  Settings,
  Star,
  Table,
  Tag,
  Trash,
  Upload,
  User,
  Bot,
  FilePenLine,
  FlaskConical,
  GitBranch,
  NotebookTabs,
  PanelsTopLeft,
  Plug,
  Route,
  ScrollText,
  Wrench,
  X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  Activity,
  Bot,
  FilePenLine,
  FlaskConical,
  GitBranch,
  NotebookTabs,
  PanelsTopLeft,
  Plug,
  Route,
  ScrollText,
  Wrench,
  AlertCircle,
  AlertTriangle,
  Apple,
  AreaChart,
  Archive,
  ArrowRight,
  ArrowRightLeft,
  BarChart3,
  Bell,
  BookMarked,
  BookOpen,
  BookOpenCheck,
  Bookmark,
  Box,
  Brain,
  BrainCircuit,
  Briefcase,
  BriefcaseBusiness,
  Building2,
  Calendar,
  Check,
  CheckCircle,
  ChefHat,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  ClipboardCheck,
  Clock,
  Code,
  Command,
  Compass,
  Copy,
  Database,
  DollarSign,
  Download,
  Eye,
  FileCheck,
  FileCheck2,
  FileCode2,
  FileText,
  Files,
  Film,
  Folder,
  FolderGit2,
  FolderOpen,
  FolderTree,
  Gauge,
  Globe,
  Grid,
  Grid2x2Plus,
  Hammer,
  HardDrive,
  Heart,
  HeartPulse,
  Home,
  House,
  Info,
  Layers,
  LayoutDashboard,
  Library,
  Image,
  Lightbulb,
  Link,
  List,
  Loader2,
  Lock,
  Megaphone,
  Menu,
  MessageSquare,
  Mic,
  MoreHorizontal,
  MoreVertical,
  Package,
  Palette,
  Paperclip,
  Pencil,
  PieChart,
  PiggyBank,
  Play,
  Plus,
  Power,
  Presentation,
  Puzzle,
  RefreshCw,
  Scale,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Spider: Bug,
  Star,
  Table,
  Tag,
  Target,
  Terminal,
  TestTube2,
  Trash,
  Trash2,
  TrendingUp,
  Upload,
  User,
  Users,
  Wallet,
  Watch,
  Workflow,
  X,
  Zap,
};

export const ICON_NAMES = Object.freeze(Object.keys(ICON_MAP));

function hasIconName(name: string): boolean {
  return Boolean(ICON_MAP[name]);
}

/**
 * Resolve a Lucide icon by string name, or pass through an existing component.
 * Falls back to `fallback` (default: FileText) for unknown names.
 */
export function resolveIcon(
  name?: string | LucideIcon | React.ReactNode,
  fallback: LucideIcon = FileText,
): LucideIcon {
  if (!name) return fallback;
  if (typeof name === "function") return name as LucideIcon;
  if (typeof name !== "string") return fallback;
  return (
    ICON_MAP[name] ??
    ICON_MAP[name.charAt(0).toUpperCase() + name.slice(1)] ??
    fallback
  );
}

/**
 * Resolve a Lucide icon by name, or return null if not found.
 * Drop-in replacement for getIcon() from sections/shared.ts.
 */
function getIcon(name?: string): LucideIcon | null {
  if (!name) return null;
  return ICON_MAP[name] ?? null;
}

/**
 * Resolve a Lucide icon by name with a guaranteed fallback.
 * Drop-in replacement for getIconOrDefault() from sections/shared.ts.
 */
function getIconOrDefault(
  name?: string,
  fallback: LucideIcon = Box,
): LucideIcon {
  return getIcon(name) ?? fallback;
}

export type { LucideIcon };
