blank_issues_enabled: true
contact_links:
  - name: Questions & Discussion
    url: https://github.com/augur-os/augur-os/discussions
    about: Ask questions and discuss ideas here
  - name: Documentation
    url: https://augur.run/more.html
    about: Read the documentation before filing an issue
