#!/usr/bin/env python3
"""
Pre-commit Hooks for Structure Enforcer Agent.

Pre-commit hook management:
- Hook installation
- Structure validation
- Auto-fix support
"""

import shutil
import sys
from datetime import datetime
from pathlib import Path
from subprocess import CompletedProcess, TimeoutExpired, run  # nosec B404
from typing import Any

def _ensure_project_paths(start: Path) -> Path:
    for candidate in (start.parent, *start.parents):
        if (
            (candidate / "pyproject.toml").is_file()
            and (candidate / "src" / "config" / "paths.py").is_file()
        ):
            for path in (candidate / "src" / "mcp", candidate, candidate / "project-brain"):
                text = str(path)
                if text not in sys.path:
                    sys.path.insert(0, text)
            return candidate
    raise RuntimeError(f"Unable to locate Augur project root from {start}")


_PROJECT_ROOT = _ensure_project_paths(Path(__file__).resolve())

from src.config.paths import get_python_executable  # noqa: E402


def _out(*args: object, **kwargs: object) -> None:
    sep = kwargs.get("sep", " ")
    end = kwargs.get("end", "\n")
    file = kwargs.get("file", sys.stdout)
    file.write(sep.join(str(arg) for arg in args) + str(end))


def _resolve_command(name: str) -> str:
    resolved = shutil.which(name)
    if not resolved:
        raise RuntimeError(f"Required executable not found in PATH: {name}")
    return resolved


def _resolve_python() -> str:
    return str(get_python_executable())


def _resolve_pre_commit_cmd() -> list[str]:
    """Resolve a runnable pre-commit command."""
    binary = shutil.which("pre-commit")
    if binary:
        return [binary]

    uv_binary = shutil.which("uvx") or shutil.which("uv")
    if uv_binary:
        return [uv_binary, "pre-commit"]

    raise RuntimeError("Neither pre-commit nor uvx/uv is available in PATH")


PRE_COMMIT_HOOK = '''#!/bin/sh
# Augur Pre-commit Hook
# Auto-generated by precommit_hooks.py

# ── Check for merge conflict markers in staged files ──
CONFLICT_FILES=$(git diff --cached --name-only --diff-filter=d -z | \
    xargs -0 grep -l '^<<<<<<<\\|^=======\\|^>>>>>>>' 2>/dev/null || true)

if [ -n "$CONFLICT_FILES" ]; then
    echo "❌ Conflict markers found in staged files:"
    echo "$CONFLICT_FILES"
    echo ""
    echo "Resolve all merge conflicts before committing."
    exit 1
fi

if command -v pre-commit >/dev/null 2>&1; then
    PRE_COMMIT_CMD="pre-commit"
else
    PRE_COMMIT_CMD="uvx pre-commit"
fi

for HOOK_ID in validate-file-placement cleanup-temp-files; do
    if ! $PRE_COMMIT_CMD run "$HOOK_ID" --hook-stage commit --config .pre-commit-config.yaml; then
        echo ""
        echo "❌ Repo pre-commit hook failed: $HOOK_ID"
        exit 1
    fi
done

echo "✅ Pre-commit checks passed."
exit 0
'''


def get_repo_root() -> Path:
    current = Path(__file__).resolve()
    for parent in [current] + list(current.parents):
        if (parent / ".git").exists():
            return parent
    return Path.cwd()


def install_hook(repo: Path) -> dict[str, Any]:
    """Install pre-commit hook."""
    hooks_dir = repo / ".git" / "hooks"
    hook_path = hooks_dir / "pre-commit"

    if not hooks_dir.exists():
        return {"error": ".git/hooks directory not found"}

    # Backup existing hook
    if hook_path.exists():
        backup = hook_path.with_suffix(".backup")
        hook_path.rename(backup)

    # Write new hook
    hook_path.write_text(PRE_COMMIT_HOOK)
    hook_path.chmod(0o755)

    return {
        "success": True,
        "hook_path": str(hook_path),
        "timestamp": datetime.now().isoformat(),
    }


def uninstall_hook(repo: Path) -> dict[str, Any]:
    """Uninstall pre-commit hook."""
    hook_path = repo / ".git" / "hooks" / "pre-commit"

    if not hook_path.exists():
        return {"error": "No pre-commit hook found"}

    # Check if it's our hook
    content = hook_path.read_text()
    if "Augur Pre-commit Hook" not in content:
        return {"error": "Hook is not an Augur hook"}

    hook_path.unlink()

    # Restore backup if exists
    backup = hook_path.with_suffix(".backup")
    if backup.exists():
        backup.rename(hook_path)

    return {"success": True}


def check_hook_status(repo: Path) -> dict[str, Any]:
    """Check pre-commit hook status."""
    hook_path = repo / ".git" / "hooks" / "pre-commit"

    status = {
        "installed": hook_path.exists(),
        "is_ours": False,
        "executable": False,
    }

    if hook_path.exists():
        content = hook_path.read_text()
        status["is_ours"] = "Augur Pre-commit Hook" in content
        status["executable"] = hook_path.stat().st_mode & 0o111 != 0

    return status


def check_conflict_markers(repo: Path | None = None) -> dict[str, Any]:
    """Check staged files for merge conflict markers. Call before any git commit."""
    repo = repo or get_repo_root()
    try:
        staged = run(
            [_resolve_command("git"), "diff", "--cached", "--name-only", "--diff-filter=d"],
            cwd=str(repo),
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )  # nosec B603
        if staged.returncode != 0 or not staged.stdout.strip():
            return {"clean": True, "files": []}

        conflict_files = []
        for filepath in staged.stdout.strip().splitlines():
            full_path = repo / filepath
            if not full_path.is_file():
                continue
            try:
                content = full_path.read_text(errors="replace")
            except Exception:
                continue
            for line in content.splitlines():
                if line.startswith(("<<<<<<<", "=======", ">>>>>>>")):
                    conflict_files.append(filepath)
                    break

        return {
            "clean": len(conflict_files) == 0,
            "files": conflict_files,
        }
    except TimeoutExpired:
        return {"clean": False, "files": [], "error": "timed out"}
    except Exception as e:
        return {"clean": False, "files": [], "error": str(e)}


def run_validation() -> dict[str, Any]:
    """Run structure validation."""
    repo = get_repo_root()

    try:
        pre_commit_cmd = _resolve_pre_commit_cmd()
        outputs: list[str] = []
        errors: list[str] = []
        returncode = 0

        for hook_id in ("validate-file-placement", "cleanup-temp-files"):
            result: CompletedProcess[str] = run(
                [*pre_commit_cmd, "run", hook_id, "--all-files", "--config", ".pre-commit-config.yaml"],
                cwd=str(repo),
                capture_output=True,
                text=True,
                timeout=180,
                check=False,
            )  # nosec B603
            if result.stdout:
                outputs.append(result.stdout)
            if result.stderr:
                errors.append(result.stderr)
            if result.returncode != 0:
                returncode = result.returncode

        return {
            "passed": returncode == 0,
            "output": "\n".join(outputs)[:1000],
            "errors": "\n".join(errors)[:500] if errors else "",
        }
    except TimeoutExpired:
        return {"error": "validation timed out after 60s"}
    except Exception as e:
        return {"error": str(e)}


def main():
    import argparse

    parser = argparse.ArgumentParser(description="Pre-commit Hooks")
    parser.add_argument("--install", action="store_true", help="Install hook")
    parser.add_argument("--uninstall", action="store_true", help="Uninstall hook")
    parser.add_argument("--status", action="store_true", help="Check status")
    parser.add_argument("--run", action="store_true", help="Run validation")
    args = parser.parse_args()

    repo = get_repo_root()

    if args.install:
        result = install_hook(repo)
        if result.get("success"):
            _out(f"✅ Pre-commit hook installed: {result['hook_path']}")
        else:
            _out(f"❌ Error: {result.get('error')}")
        return 0 if result.get("success") else 1

    if args.uninstall:
        result = uninstall_hook(repo)
        if result.get("success"):
            _out("✅ Pre-commit hook uninstalled")
        else:
            _out(f"❌ Error: {result.get('error')}")
        return 0 if result.get("success") else 1

    if args.run:
        result = run_validation()
        if result.get("passed"):
            _out("✅ Validation passed!")
        else:
            _out("❌ Validation failed")
            if result.get("output"):
                _out(result["output"])
        return 0 if result.get("passed") else 1

    # Default: status
    status = check_hook_status(repo)

    _out("🔗 Pre-commit Hook Status\n")
    _out(f"   Installed: {'✅' if status['installed'] else '❌'}")

    if status["installed"]:
        _out(f"   Ours: {'✅' if status['is_ours'] else '❌'}")
        _out(f"   Executable: {'✅' if status['executable'] else '❌'}")

    if not status["installed"]:
        _out("\n   Run with --install to set up pre-commit hook")

    return 0


if __name__ == "__main__":
    sys.exit(main())
