"""auto-api-health: API route health monitoring and TODO_BUG marker creation.

Extracted from HardeningLoop execute_action (api-route-health category, ADR-200).
This module has no autonomous scanner — findings are fed externally by
dashboard health monitors or manual ops triggers.
"""
from __future__ import annotations


import importlib.util as _augur_importlib_util
import sys as _augur_sys
from pathlib import Path as _AugurPath

_augur_bootstrap_start = _AugurPath(__file__).resolve()
for _augur_bootstrap_parent in (_augur_bootstrap_start.parent, *_augur_bootstrap_start.parents):
    _augur_bootstrap_path = _augur_bootstrap_parent / "daemon" / "scripts" / "bootstrap_paths.py"
    if _augur_bootstrap_path.is_file():
        break
else:
    raise RuntimeError(f"Unable to locate shared skill bootstrap from {_augur_bootstrap_start}")

_augur_bootstrap_spec = _augur_importlib_util.spec_from_file_location(
    "_augur_shared_bootstrap_paths", _augur_bootstrap_path
)
if _augur_bootstrap_spec is None or _augur_bootstrap_spec.loader is None:
    raise RuntimeError(f"Unable to load shared skill bootstrap from {_augur_bootstrap_path}")
_augur_bootstrap_module = _augur_importlib_util.module_from_spec(_augur_bootstrap_spec)
_augur_sys.modules[_augur_bootstrap_spec.name] = _augur_bootstrap_module
_augur_bootstrap_spec.loader.exec_module(_augur_bootstrap_module)
_augur_bootstrap_module.ensure_project_paths(__file__)
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from src.lib.ops_protocol import FixResult, OpsContext, ScanResult

name = "auto-api-health"

_TODO_BUG_COMMENT = "# TODO_BUG: API route health failure — see hardening report"


def _commit_files(project_root: Path, message: str, paths: list[str]) -> str | None:
    """Stage specific paths and commit. Returns commit hash or None."""
    for p in paths:
        subprocess.run(
            ["git", "add", p],
            capture_output=True,
            cwd=str(project_root),
        )
    result = subprocess.run(
        ["git", "diff", "--cached", "--quiet"],
        capture_output=True,
        cwd=str(project_root),
    )
    if result.returncode == 0:
        return None
    result = subprocess.run(
        ["git", "commit", "-m", message],
        capture_output=True,
        text=True,
        cwd=str(project_root),
    )
    if result.returncode == 0:
        rev = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            cwd=str(project_root),
        )
        return rev.stdout.strip() if rev.returncode == 0 else None
    return None


def _append_to_report(report_dir: Path, category: str, detail: str, file_path: str) -> None:
    """Append a finding to today's hardening report, skipping duplicates."""
    report_dir.mkdir(parents=True, exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    report_file = report_dir / f"hardening-{today}.md"
    entry = f"- **{category}**: {detail} ({file_path})\n"
    if not report_file.exists():
        report_file.write_text(
            f"# Hardening Report — {today}\n\n"
            f"Auto-generated by adaptive loop engine.\n\n"
        )
    existing = report_file.read_text()
    if entry in existing:
        return  # Skip duplicate
    with open(report_file, "a") as f:
        f.write(entry)


def scan(ctx: OpsContext) -> ScanResult:
    """No autonomous scanner — findings are fed externally."""
    return ScanResult(
        issues=[],
        summary="api-health: no autonomous scanner (findings fed externally)",
        severity="info",
    )


def fix(ctx: OpsContext, issues: list[dict]) -> FixResult:
    """Write finding to hardening report and create TODO_BUG marker if applicable."""
    if ctx.dry_run:
        return FixResult(
            success=True,
            summary=f"Dry run: would report {len(issues)} API health issue(s)",
        )

    if not issues:
        return FixResult(success=True, summary="No API health issues to process")

    report_dir = ctx.project_root / "docs" / "generated" / "hardening"
    changed_paths: list[str] = []

    for issue in issues:
        detail = issue.get("detail", issue.get("action", "unknown"))
        file_rel = issue.get("file", "n/a")
        _append_to_report(report_dir, "api-route-health", detail, file_rel)

        # Write TODO_BUG marker to source file when applicable
        if file_rel and file_rel != "n/a":
            source_file = ctx.project_root / file_rel
            if source_file.exists() and source_file.suffix in (".ts", ".tsx", ".py"):
                content = source_file.read_text()
                if _TODO_BUG_COMMENT not in content:
                    source_file.write_text(_TODO_BUG_COMMENT + "\n" + content)
                    changed_paths.append(file_rel)

    changed_paths.append(str(report_dir))
    commit = _commit_files(
        ctx.project_root,
        "chore(adaptive): hardening report update (api-health)",
        paths=changed_paths,
    )
    return FixResult(
        success=True,
        actions=[{"commit": commit}] if commit else [],
        changes=changed_paths,
        summary=f"Reported {len(issues)} API health issue(s) to hardening report",
    )
