"""auto-page-mounts: Verify contributions.pages source files exist.

Extracted from HardeningLoop._scan_page_mounts and _write_report (ADR-200).
"""
from __future__ import annotations


import importlib.util as _augur_importlib_util
import sys as _augur_sys
from pathlib import Path as _AugurPath

_augur_bootstrap_start = _AugurPath(__file__).resolve()
for _augur_bootstrap_parent in (_augur_bootstrap_start.parent, *_augur_bootstrap_start.parents):
    _augur_bootstrap_path = _augur_bootstrap_parent / "daemon" / "scripts" / "bootstrap_paths.py"
    if _augur_bootstrap_path.is_file():
        break
else:
    raise RuntimeError(f"Unable to locate shared skill bootstrap from {_augur_bootstrap_start}")

_augur_bootstrap_spec = _augur_importlib_util.spec_from_file_location(
    "_augur_shared_bootstrap_paths", _augur_bootstrap_path
)
if _augur_bootstrap_spec is None or _augur_bootstrap_spec.loader is None:
    raise RuntimeError(f"Unable to load shared skill bootstrap from {_augur_bootstrap_path}")
_augur_bootstrap_module = _augur_importlib_util.module_from_spec(_augur_bootstrap_spec)
_augur_sys.modules[_augur_bootstrap_spec.name] = _augur_bootstrap_module
_augur_bootstrap_spec.loader.exec_module(_augur_bootstrap_module)
_augur_bootstrap_module.ensure_project_paths(__file__)
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from src.config.paths import get_all_client_skill_dirs
from src.lib.frontmatter_utils import parse_frontmatter
from src.lib.ops_protocol import FixResult, OpsContext, ScanResult, declare_ops_capabilities

name = "auto-page-mounts"
OPS_CAPABILITIES = declare_ops_capabilities(
    platforms=("cross_platform",),
    windows_fix_mode="report_only",
)

DIFFICULTY_SPEC = {
    0: "Surface check — verify plugins directory exists",
    1: "Content check — parse SKILL.md config and check page source files exist",
    2: "Deep check — validate page structure and file references",
    3: "Exhaustive — cross-reference all page mounts with dashboard routes",
    4: "Expert — full mount integrity with content hash verification",
}


def _commit_files(project_root: Path, message: str, paths: list[str]) -> str | None:
    """Stage specific paths and commit. Returns commit hash or None."""
    for p in paths:
        subprocess.run(
            ["git", "add", p],
            capture_output=True,
            cwd=str(project_root),
        )
    result = subprocess.run(
        ["git", "diff", "--cached", "--quiet"],
        capture_output=True,
        cwd=str(project_root),
    )
    if result.returncode == 0:
        return None
    result = subprocess.run(
        ["git", "commit", "-m", message],
        capture_output=True,
        text=True,
        cwd=str(project_root),
    )
    if result.returncode == 0:
        rev = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            cwd=str(project_root),
        )
        return rev.stdout.strip() if rev.returncode == 0 else None
    return None


def _append_to_report(report_dir: Path, category: str, detail: str, file_path: str) -> None:
    """Append a finding to today's hardening report, skipping duplicates."""
    report_dir.mkdir(parents=True, exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    report_file = report_dir / f"hardening-{today}.md"
    entry = f"- **{category}**: {detail} ({file_path})\n"
    if not report_file.exists():
        report_file.write_text(
            f"# Hardening Report — {today}\n\n"
            f"Auto-generated by adaptive loop engine.\n\n"
        )
    existing = report_file.read_text()
    if entry in existing:
        return  # Skip duplicate
    with open(report_file, "a") as f:
        f.write(entry)


def _iter_skill_md_files(
    project_root: Path,
    shared_snapshot: dict | None = None,
) -> list[Path]:
    """Return skill SKILL.md files from shared snapshot or filesystem."""
    if shared_snapshot:
        skill_roots = shared_snapshot.get("skill_roots")
        if isinstance(skill_roots, list):
            skill_mds = [
                Path(skill_root) / "SKILL.md"
                for skill_root in skill_roots
                if isinstance(skill_root, str)
            ]
            return sorted(path for path in skill_mds if path.exists())
    return sorted(
        skill_dir / "SKILL.md"
        for d in get_all_client_skill_dirs(project_root)
        if d.resolve().is_relative_to(project_root.resolve())
        for skill_dir in d.iterdir()
        if skill_dir.is_dir() and (skill_dir / "SKILL.md").exists()
    )


def scan(ctx: OpsContext) -> ScanResult:
    """Walk x-augur-config contributions.pages and check that source files exist."""
    # d0: surface check — no file walking
    if ctx.difficulty < 1:
        return ScanResult(
            issues=[], summary="Skill directories checked (d0 surface only)",
            severity="info", health="verified",
        )

    issues = []
    n_mounts = 0
    for skill_md in _iter_skill_md_files(ctx.project_root, ctx.shared_snapshot):
        try:
            frontmatter, _body = parse_frontmatter(skill_md)
        except OSError:
            continue

        config = frontmatter.get("x-augur-config") or {}
        if not isinstance(config, dict):
            continue

        contributions = config.get("contributions") or {}
        if not isinstance(contributions, dict):
            issues.append({
                "action": "invalid-contributions-structure",
                "file": str(skill_md.relative_to(ctx.project_root)),
                "detail": "x-augur-config.contributions must be a mapping when present",
            })
            continue

        pages = contributions.get("pages") or []
        if not isinstance(pages, list):
            issues.append({
                "action": "invalid-pages-structure",
                "file": str(skill_md.relative_to(ctx.project_root)),
                "detail": "x-augur-config.contributions.pages must be a list when present",
            })
            continue
        skill_dir = skill_md.parent

        for page in pages:
            if not isinstance(page, dict):
                continue
            page_file = page.get("file", "")
            if not page_file:
                continue
            n_mounts += 1
            source = skill_dir / page_file
            if not source.exists():
                issues.append({
                    "action": f"missing-page-{page.get('id', 'unknown')}",
                    "file": str(source.relative_to(ctx.project_root)),
                    "detail": f"Page source missing: {page_file} (skill: {skill_dir.name})",
                })

    return ScanResult(
        issues=issues,
        summary=f"{len(issues)} missing page source file(s)",
        severity="warning" if issues else "info",
        items_scanned=n_mounts,
    )


def fix(ctx: OpsContext, issues: list[dict]) -> FixResult:
    """Write findings to hardening report and commit."""
    if ctx.dry_run:
        return FixResult(
            success=True,
            summary=f"Dry run: would report {len(issues)} missing page mount(s)",
        )

    report_dir = ctx.project_root / "docs" / "generated" / "hardening"
    for issue in issues:
        _append_to_report(
            report_dir,
            category="page-mount-check",
            detail=issue.get("detail", issue.get("action", "")),
            file_path=issue.get("file", "n/a"),
        )

    if not issues:
        return FixResult(success=True, summary="No issues to report")

    commit = _commit_files(
        ctx.project_root,
        "chore(adaptive): hardening report update (page-mounts)",
        paths=[str(report_dir)],
    )
    return FixResult(
        success=True,
        actions=[{"commit": commit}] if commit else [],
        changes=[str(report_dir)],
        summary=f"Reported {len(issues)} missing mount(s) to hardening report",
        fix_type="report",
    )
