"""auto-stale-paths: enforce ADR-270 folder/path migration drift.

Scans active code, workflow, and operational docs for high-signal holdouts:
- repo-local runtime paths
- legacy augur data references
- legacy augur MCP fallbacks
- placeholder ADR-270 structure markers

At d1+, issues with a clear canonical replacement are auto-fixed via
deterministic text replacement. Ambiguous issues remain report-only.
"""
from __future__ import annotations


import importlib.util as _augur_importlib_util
import sys as _augur_sys
from pathlib import Path as _AugurPath

_augur_bootstrap_start = _AugurPath(__file__).resolve()
for _augur_bootstrap_parent in (_augur_bootstrap_start.parent, *_augur_bootstrap_start.parents):
    _augur_bootstrap_path = _augur_bootstrap_parent / "daemon" / "scripts" / "bootstrap_paths.py"
    if _augur_bootstrap_path.is_file():
        break
else:
    raise RuntimeError(f"Unable to locate shared skill bootstrap from {_augur_bootstrap_start}")

_augur_bootstrap_spec = _augur_importlib_util.spec_from_file_location(
    "_augur_shared_bootstrap_paths", _augur_bootstrap_path
)
if _augur_bootstrap_spec is None or _augur_bootstrap_spec.loader is None:
    raise RuntimeError(f"Unable to load shared skill bootstrap from {_augur_bootstrap_path}")
_augur_bootstrap_module = _augur_importlib_util.module_from_spec(_augur_bootstrap_spec)
_augur_sys.modules[_augur_bootstrap_spec.name] = _augur_bootstrap_module
_augur_bootstrap_spec.loader.exec_module(_augur_bootstrap_module)
_augur_bootstrap_module.ensure_project_paths(__file__)
import ast
import json
import re
import subprocess
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

from src.config.paths import get_runtime_dir
from src.lib.llm_retry import resolve_cli as _find_cli
from src.lib.staged_skill_catalog import is_staging_payload_path
from src.lib.ops_protocol import (
    FixResult,
    OpsContext,
    ScanResult,
    declare_ops_capabilities,
    check_intentional_skip,
    write_report,
)

name = "auto-stale-paths"
OPS_CAPABILITIES = declare_ops_capabilities(
    platforms=("cross_platform",),
    windows_fix_mode="auto_fix",
)

_PLACEHOLDER_README = "Generated by ADR-270 migration. Update from SKILL.md."
_REPORT_NAME = "adr270-enforcement-latest.json"
_TEXT_SUFFIXES = {
    ".md",
    ".py",
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".mjs",
    ".cjs",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".sh",
}
_DOC_SUFFIXES = {".md"}
_SKIP_DIR_NAMES = {
    ".git",
    ".hg",
    ".svn",
    ".next",
    "node_modules",
    "runtime",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    "dist",
    "build",
    "tests",
}
_SKIP_PATH_PARTS = {
    "docs/decisions",
    "docs/plans",
    "docs/superpowers",
    "docs/generated",
    "docs/agent-topics",
    ".antigravity",
    ".claude/agents",
    "skills",
    ".gemini/skills",
    ".gemini/workflows",
    ".gemini/topics",
    ".gemini/memory",
}
_SKIP_EXACT_PATHS = {
    "AGENTS.md",
    "CLAUDE.md",
    "CODEX.md",
    ".antigravity/instructions.md",
    ".github/copilot-instructions.md",
    # audit_logging.py is itself a path-drift detector — its regex patterns name
    # runtime/ paths to FIND them elsewhere; skip it like the sibling scanners
    # below so the stale-paths loop does not flag its own detection patterns.
    ".github/scripts/audit_logging.py",
    ".github/scripts/scan_stale_paths.py",
    ".github/scripts/stale_config.py",
    ".github/scripts/stale_scanners.py",
    ".github/scripts/validate_file_placement.py",
    ".github/scripts/validate_skill_structure.py",
    ".github/scripts/validate_structure.py",
    ".gemini/GEMINI.md",
    ".opencode/AGENTS.md",
    # Safety-net entry: if someone accidentally runs `npm install` in apps/dashboard/
    # (it's pnpm-managed per ADR-759), the resulting package-lock.json is a generated
    # artifact whose runtime/registry tokens are not real path drift. The on-disk file
    # is intentionally absent post-ADR-759; this skip entry remains as a contract guard
    # exercised by test_scan_skips_generated_npm_package_lock.
    "apps/dashboard/package-lock.json",
    "apps/dashboard/public/licenses.json",
    "apps/dashboard/lib/server/skillReadme.ts",
    "project-brain/capabilities/skills/daemon/scripts/ops/stale_paths.py",
    "scripts/check-skill-structure.sh",
    "scripts/hooks/run-hook.mjs",
    "skills/platform-admin/scripts/augur_nightly_checks.py",
    "skills/platform-admin/scripts/migrate_to_monorepo.py",
    "project-brain/capabilities/skills/platform-admin/scripts/augur_nightly_checks.py",
    "project-brain/capabilities/skills/platform-admin/scripts/migrate_to_monorepo.py",
    "project-brain/capabilities/skills/routine-coverage/scripts/adaptive_hub_coverage_ops.py",
    "project-brain/capabilities/skills/routine-coverage/scripts/brain_hub_coverage_ops.py",
    "project-brain/capabilities/skills/routine-coverage/scripts/life_hub_coverage_ops.py",
    "project-brain/decisions/adrs/adrs-index.json",
    "apps/dashboard/scripts/skill-scripts/generate_hardening_adr.py",
    "apps/dashboard/scripts/skill-scripts/_hardening_implementation.py",
    "skills/auto-test-webmcp/scripts/webmcp_ops.py",
    "skills/routine-vault/scripts/markdown_ops.py",
    "skills/rag/scripts/_scanners_knowledge.py",
    "src/mcp/augur_mcp/infrastructure/browse.py",
    # Live Brain coverage route contains augur/data/ in legacyPatterns arrays — documentation, not code
    "apps/dashboard/app/api/auto-brain-hub-coverage/route.ts",
}


@dataclass(frozen=True)
class DriftRule:
    action: str
    category: str
    regexes: tuple[re.Pattern[str], ...]
    summary_label: str
    suggestion: str
    # Deterministic replacements: list of (pattern, replacement) pairs.
    # When non-empty, issues matching this rule are auto-fixable via sed.
    sed_replacements: tuple[tuple[re.Pattern[str], str], ...] = ()


_RUNTIME_TOKEN = "runtime" + "/"
_AUGUR_DATA_TOKEN = "augur" + "/" + "data" + "/"
_AUGUR_MCP_TOKEN = "augur" + "/" + "mcp" + "/"
_LEGACY_DASHBOARD_TOKEN = "src" + "/" + "dashboard"


_DRIFT_RULES = (
    DriftRule(
        action="legacy-runtime-path",
        category="runtime",
        regexes=(
            re.compile(r"(?<![A-Za-z0-9_-])(?:data/)?" + re.escape(_RUNTIME_TOKEN)),
            re.compile(r"\bPath\(\s*[\"']runtime[\"']\s*\)"),
            re.compile(r"\b(?:path\.)?join\([^#\n]*[\"']runtime[\"']"),
            re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*\s*/\s*[\"']runtime[\"']"),
            re.compile(r"process\.env\.[A-Z0-9_]+\s*\|\|\s*[\"']runtime[\"']"),
        ),
        summary_label="runtime",
        suggestion="Use src.config.paths state/logs/cache helpers instead of repo-local runtime paths.",
    ),
    DriftRule(
        action="legacy-augur-data-path",
        category="skill-data",
        regexes=(
            re.compile(r"(?<![A-Za-z0-9_])" + re.escape(_AUGUR_DATA_TOKEN)),
            re.compile(r"(?<![A-Za-z0-9_])" + re.escape(_AUGUR_DATA_TOKEN[:-1]) + r"(?:[\"'`)]|$)"),
            re.compile(r"[\"']augur[\"']\s*/\s*[\"']data[\"']"),
            re.compile(r"\b(?:path\.)?join\([^#\n]*[\"']augur[\"'][^#\n]*[\"']data[\"']"),
        ),
        summary_label="augur data",
        suggestion="Use vault-first skill data helpers or assets fallbacks instead of legacy augur data paths.",
    ),
    DriftRule(
        action="legacy-augur-mcp-path",
        category="skill-mcp",
        regexes=(
            re.compile(r"(?<![A-Za-z0-9_])" + re.escape(_AUGUR_MCP_TOKEN)),
            re.compile(r"(?<![A-Za-z0-9_])" + re.escape(_AUGUR_MCP_TOKEN[:-1]) + r"(?:[\"'`)]|$)"),
            re.compile(r"[\"']augur[\"']\s*/\s*[\"']mcp[\"']"),
            re.compile(r"\b(?:path\.)?join\([^#\n]*[\"']augur[\"'][^#\n]*[\"']mcp[\"']"),
        ),
        summary_label="augur mcp",
        suggestion="Use scripts/mcp/ as the canonical MCP tool location.",
        sed_replacements=(
            # scripts/mcp/ -> scripts/mcp/
            (re.compile(r"(?<![A-Za-z0-9_])scripts/mcp/"), "scripts/mcp/"),
            # scripts/mcp (no trailing slash) -> scripts/mcp
            (re.compile(r"(?<![A-Za-z0-9_])scripts/mcp(?![A-Za-z0-9_/])"), "scripts/mcp"),
            # Path segment: / "scripts" / "mcp" -> / "scripts" / "mcp"
            (re.compile(r"""/\s*["']augur["']\s*/\s*["']mcp["']"""), """/ "scripts" / "mcp\""""),
        ),
    ),
    DriftRule(
        action="legacy-dashboard-path",
        category="dashboard-path",
        regexes=(
            # Bare path: src/dashboard or src/lib/dashboard
            re.compile(r"""(?<![A-Za-z0-9_])src/dashboard(?![A-Za-z0-9_])"""),
            re.compile(r"""(?<![A-Za-z0-9_])src/lib/dashboard(?![A-Za-z0-9_])"""),
            # Path segment construction: / "src" / "dashboard"
            re.compile(r"""/\s*[\"']src[\"']\s*/\s*[\"']dashboard[\"']"""),
            # Path segment with intermediate: / "src/lib" / "dashboard"
            re.compile(r"""/\s*[\"']src/lib[\"']\s*/\s*[\"']dashboard[\"']"""),
            # os.path.join style: join(..., "src", ..., "dashboard")
            re.compile(r"""\b(?:path\.)?join\([^#\n]*[\"']src[\"'][^#\n]*[\"']dashboard[\"']"""),
        ),
        summary_label="legacy dashboard path",
        suggestion="Dashboard moved to apps/dashboard (ADR-270). Update path to PROJECT_ROOT / 'apps' / 'dashboard'.",
        sed_replacements=(
            # src/lib/dashboard -> apps/dashboard (must come before src/dashboard)
            (re.compile(r"(?<![A-Za-z0-9_])src/lib/dashboard(?![A-Za-z0-9_])"), "apps/dashboard"),
            # src/dashboard -> apps/dashboard
            (re.compile(r"(?<![A-Za-z0-9_])src/dashboard(?![A-Za-z0-9_])"), "apps/dashboard"),
            # Path segment: / "apps" / "dashboard" -> / "apps" / "dashboard"
            (re.compile(r"""/\s*["']src["']\s*/\s*["']dashboard["']"""), """/ "apps" / "dashboard\""""),
            # Path segment: / "apps" / "dashboard" -> / "apps" / "dashboard"
            (re.compile(r"""/\s*["']src/lib["']\s*/\s*["']dashboard["']"""), """/ "apps" / "dashboard\""""),
        ),
    ),
    DriftRule(
        action="stale-adr270-marker",
        category="structure-marker",
        regexes=(re.compile(re.escape(_PLACEHOLDER_README)),),
        summary_label="markers",
        suggestion="Regenerate augur/README.md from SKILL.md or replace the placeholder with canonical docs.",
    ),
)


def _should_skip_file(path: Path) -> bool:
    if path.suffix.lower() not in _TEXT_SUFFIXES:
        return True
    rel = path.as_posix()
    if rel in _SKIP_EXACT_PATHS:
        return True
    if is_staging_payload_path(path):
        return True
    parts = path.parts
    if any(part in _SKIP_DIR_NAMES for part in parts):
        return True
    return any(rel == prefix or rel.startswith(f"{prefix}/") for prefix in _SKIP_PATH_PARTS)


def _iter_repo_files(project_root: Path) -> list[Path]:
    files: list[Path] = []
    for path in sorted(project_root.rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(project_root)
        if _should_skip_file(rel):
            continue
        files.append(path)
    return files


def _match_rule(line: str, rule: DriftRule) -> str | None:
    for regex in rule.regexes:
        match = regex.search(line)
        if match:
            return match.group(0)
    return None


def _is_python_prose_line(path: Path, line: str) -> bool:
    """Skip Python docstring/comment prose when scanning for executable drift."""
    if path.suffix.lower() != ".py":
        return False
    stripped = line.lstrip()
    return stripped.startswith(('"""', "'''", "#"))


def _python_docstring_line_numbers(content: str) -> set[int]:
    """Return line numbers occupied by real Python docstrings."""
    try:
        tree = ast.parse(content)
    except SyntaxError:
        return set()

    lines: set[int] = set()
    nodes: list[ast.AST] = [tree]
    nodes.extend(
        node
        for node in ast.walk(tree)
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
    )
    for node in nodes:
        body = getattr(node, "body", None)
        if not body:
            continue
        first = body[0]
        if not isinstance(first, ast.Expr):
            continue
        value = first.value
        if not isinstance(value, ast.Constant) or not isinstance(value.value, str):
            continue
        start = getattr(value, "lineno", None)
        end = getattr(value, "end_lineno", start)
        if start is None or end is None:
            continue
        lines.update(range(start, end + 1))
    return lines


def _scan_file(project_root: Path, path: Path, rel_override: str | None = None) -> list[dict]:
    try:
        content = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []

    rel = rel_override or path.relative_to(project_root).as_posix()
    python_docstring_lines = (
        _python_docstring_line_numbers(content)
        if path.suffix.lower() == ".py"
        else set()
    )
    issues: list[dict] = []

    for line_number, line in enumerate(content.splitlines(), start=1):
        if not line.strip():
            continue
        if line_number in python_docstring_lines:
            continue
        if check_intentional_skip(path, line_number):
            continue
        for rule in _DRIFT_RULES:
            snippet = _match_rule(line, rule)
            if not snippet:
                continue
            if _is_python_prose_line(path, line):
                continue
            if rule.action == "legacy-runtime-path" and "legacyRuntimeDir" in line:
                continue
            if rule.action == "legacy-runtime-path" and "runtime/config root" in line:
                continue
            strategy = "sed" if rule.sed_replacements else "report"
            issues.append(
                {
                    "action": rule.action,
                    "category": rule.category,
                    "file": rel,
                    "line": line_number,
                    "detail": f"{rule.summary_label} drift: {snippet.strip()}",
                    "match": snippet.strip(),
                    "line_text": line.strip(),
                    "suggestion": rule.suggestion,
                    "fix_strategy": strategy,
                }
            )
    return issues


# Shell config files outside the repo that may reference Augur paths
_SHELL_CONFIG_FILES = (
    ".zshrc",
    ".bashrc",
    ".bash_profile",
    ".profile",
)


def _scan_shell_configs(project_root: Path) -> list[dict]:
    """Scan user shell configs for stale Augur path references."""
    home = Path.home()
    issues: list[dict] = []
    for name in _SHELL_CONFIG_FILES:
        path = home / name
        if path.is_file():
            issues.extend(_scan_file(project_root, path, rel_override=f"~/{name}"))
    return issues


def _split_documentation_issues(issues: list[dict]) -> tuple[list[dict], list[dict]]:
    """Split issues into actionable code/config drift and documentation drift."""
    actionable: list[dict] = []
    documentation: list[dict] = []
    for issue in issues:
        suffix = Path(issue.get("file", "")).suffix.lower()
        if suffix in _DOC_SUFFIXES:
            documentation.append(issue)
        else:
            actionable.append(issue)
    return actionable, documentation


def _collect_drift_issues(project_root: Path) -> tuple[list[dict], list[dict]]:
    """Scan the repo and shell configs, return actionable issues plus documentation-only drift."""
    all_issues: list[dict] = []
    for path in _iter_repo_files(project_root):
        all_issues.extend(_scan_file(project_root, path))
    # Also scan shell configs outside the repo for stale Augur path references
    all_issues.extend(_scan_shell_configs(project_root))
    return _split_documentation_issues(all_issues)


def _cached_pending_scan() -> ScanResult | None:
    """Reuse the last ADR-270 report for dry-run d0 scans when available."""
    report_path = get_runtime_dir() / "reports" / _REPORT_NAME
    hardening_report_path = get_runtime_dir() / "adaptive" / "reports" / "hardening-latest.json"
    scanner_mtime = Path(__file__).stat().st_mtime

    if hardening_report_path.is_file():
        try:
            hardening_report = json.loads(hardening_report_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            hardening_report = None
        if hardening_report is not None:
            hardening_mtime = hardening_report_path.stat().st_mtime
            stale_report_mtime = report_path.stat().st_mtime if report_path.is_file() else -1
            if hardening_mtime >= stale_report_mtime:
                for category in hardening_report.get("categories", []):
                    if category.get("name") != name:
                        continue
                    actionable_count = int(category.get("actionable_count", 0) or 0)
                    issues = [
                        {
                            "action": "cached-adr270-drift",
                            "category": "cached-loop-status",
                            "detail": "cached ADR-270 actionable drift",
                            "file": "(cached)",
                            "fix_strategy": "report",
                        }
                        for _ in range(actionable_count)
                    ]
                    return ScanResult(
                        issues=issues,
                        summary=(
                            f"{actionable_count} ADR-270 executable/config drift issue(s)"
                            " [latest hardening report]"
                        ),
                        severity="warning" if actionable_count else "info",
                        health="degraded" if actionable_count else "verified",
                    )
                # A newer hardening report without this category should invalidate
                # older ADR-270 cache data rather than surfacing stale placeholders.
                return None

    if not report_path.is_file():
        return None
    if report_path.stat().st_mtime < scanner_mtime:
        return None

    try:
        report = json.loads(report_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None

    summary = report.get("summary", {})
    actionable_count = int(summary.get("issue_count", 0) or 0)
    documentation_count = int(summary.get("documentation_issue_count", 0) or 0)
    issues = [
        {
            "action": "cached-adr270-drift",
            "category": "cached-report",
            "detail": "cached ADR-270 actionable drift",
            "file": "(cached)",
            "fix_strategy": "report",
        }
        for _ in range(actionable_count)
    ]
    summary_text = f"{actionable_count} ADR-270 executable/config drift issue(s) [cached report]"
    if documentation_count:
        summary_text += f"; {documentation_count} documentation issue(s) tracked separately"
    return ScanResult(
        issues=issues,
        summary=summary_text,
        severity="warning" if actionable_count else "info",
        health="degraded" if actionable_count else "verified",
    )


def scan(ctx: OpsContext) -> ScanResult:
    """Autonomously detect active ADR-270 path/folder drift."""
    if not ctx.project_root.exists():
        return ScanResult(
            issues=[],
            summary="Project root missing",
            severity="info",
            health="broken",
        )

    if ctx.dry_run and ctx.difficulty < 1:
        cached = _cached_pending_scan()
        if cached is not None:
            return cached

    issues, documentation_issues = _collect_drift_issues(ctx.project_root)

    max_issues = int(ctx.config.get("max_issues", 250))
    actionable_total = len(issues)
    doc_total = len(documentation_issues)
    truncated = False
    if len(issues) > max_issues:
        issues = issues[:max_issues]
        truncated = True

    counts = Counter(issue["category"] for issue in issues)
    count_parts = [f"{key}={counts[key]}" for key in sorted(counts)]
    suffix = " (truncated)" if truncated else ""
    summary = (
        f"{len(issues)} ADR-270 executable/config drift issue(s)"
        + (f": {', '.join(count_parts)}" if count_parts else "")
        + suffix
    )
    if doc_total:
        summary += f"; {doc_total} documentation issue(s) tracked separately"
        if doc_total > max_issues:
            summary += " (docs truncated in report)"
    return ScanResult(
        issues=issues,
        summary=summary,
        severity="warning" if issues else "info",
        health="degraded" if issues else "verified",
    )


def _write_enforcement_report(ctx: OpsContext, issues: list[dict]) -> FixResult:
    _, documentation_issues = _collect_drift_issues(ctx.project_root)
    max_doc_issues = int(ctx.config.get("max_doc_issues", 250))
    doc_truncated = False
    documentation_total = len(documentation_issues)
    if len(documentation_issues) > max_doc_issues:
        documentation_issues = documentation_issues[:max_doc_issues]
        doc_truncated = True

    counts = Counter(issue.get("category", "unknown") for issue in issues)
    documentation_counts = Counter(
        issue.get("category", "unknown") for issue in documentation_issues
    )
    report = {
        "summary": {
            "issue_count": len(issues),
            "documentation_issue_count": documentation_total,
            "by_category": dict(sorted(counts.items())),
            "documentation_by_category": dict(sorted(documentation_counts.items())),
            "documentation_truncated": doc_truncated,
        },
        "issues": issues,
        "documentation_issues": documentation_issues,
    }
    report_path = write_report(ctx, _REPORT_NAME, report)
    return FixResult(
        success=True,
        actions=[{"report": str(report_path), "mode": "report-only"}],
        changes=[str(report_path)],
        summary=(
            f"ADR-270 drift report written with {len(issues)} executable/config issue(s)"
            + (
                f" and {documentation_total} documentation issue(s)"
                if documentation_total
                else ""
            )
        ),
        fix_type="report",
    )


def _get_sed_rules() -> dict[str, tuple[tuple[re.Pattern[str], str], ...]]:
    """Build a lookup from action name to sed replacement pairs."""
    return {rule.action: rule.sed_replacements for rule in _DRIFT_RULES if rule.sed_replacements}


def _fix_with_sed(ctx: OpsContext, issues: list[dict]) -> FixResult:
    """Apply deterministic text replacements for issues with clear canonical paths.

    Groups issues by file, reads each file once, applies all applicable sed
    replacements, and writes back only if content changed.
    """
    sed_rules = _get_sed_rules()

    # Group issues by file
    files_to_fix: dict[str, list[dict]] = {}
    for issue in issues:
        file_rel = issue.get("file", "")
        if not file_rel or file_rel.startswith("(") or file_rel.startswith("~"):
            continue  # Skip cached/shell-config issues
        files_to_fix.setdefault(file_rel, []).append(issue)

    all_changes: list[str] = []
    all_actions: list[dict] = []

    for file_rel, file_issues in sorted(files_to_fix.items()):
        file_path = ctx.project_root / file_rel
        if not file_path.is_file():
            continue

        try:
            original = file_path.read_text(encoding="utf-8")
        except OSError:
            all_actions.append({"skipped": file_rel, "reason": "read error"})
            continue

        content = original
        replacements_applied = 0

        for issue in file_issues:
            action = issue.get("action", "")
            replacements = sed_rules.get(action, ())
            for pattern, replacement in replacements:
                new_content = pattern.sub(replacement, content)
                if new_content != content:
                    replacements_applied += content.count(pattern.pattern) or 1
                    content = new_content

        if content != original:
            file_path.write_text(content, encoding="utf-8")
            all_changes.append(file_rel)
            all_actions.append({
                "fixed": file_rel,
                "replacements": replacements_applied,
            })
        else:
            all_actions.append({"skipped": file_rel, "reason": "no change after sed"})

    return FixResult(
        success=True,
        actions=all_actions,
        changes=all_changes,
        summary=(
            f"sed-fixed {len(all_changes)} file(s) with stale path references"
            if all_changes
            else "No sed-fixable changes applied"
        ),
        fix_type="code-fix" if all_changes else "report",
    )


def _fix_with_ai(ctx: OpsContext, issues: list[dict]) -> FixResult:
    cli_path = _find_cli()
    if not cli_path:
        return FixResult(
            success=False,
            summary="No Claude CLI found — cannot auto-fix stale path issues",
        )

    all_changes: list[str] = []
    all_actions: list[dict] = []
    overall_success = True

    for issue in issues:
        detail = issue.get("detail", "")
        file_rel = issue.get("file", "")

        prompt = (
            f"Fix the following stale path reference: {detail}. "
            f"File: {file_rel}. "
            f"Update the path to the correct current location. "
            f"Make the minimal change needed. "
            f"Do NOT use @ts-ignore or workaround comments."
        )
        max_turns = str(ctx.config.get("max_turns", 8))
        fix_timeout = ctx.config.get("fix_timeout", 180)
        result = subprocess.run(
            [
                cli_path,
                "--print",
                "--max-turns",
                max_turns,
                "--allowedTools",
                "Read,Edit,Write,Grep,Glob",
                "-p",
                prompt,
            ],
            capture_output=True,
            text=True,
            timeout=fix_timeout,
            cwd=str(ctx.project_root),
        )
        if result.returncode != 0:
            overall_success = False
            all_actions.append({"failed": file_rel, "exit": result.returncode})
        else:
            all_changes.append(file_rel)
            all_actions.append({"fixed": file_rel})

    return FixResult(
        success=overall_success,
        actions=all_actions,
        changes=all_changes,
        summary=(
            f"AI-fixed {len(all_changes)} stale path issue(s)"
            if all_changes
            else "No changes made"
        ),
    )


def fix(ctx: OpsContext, issues: list[dict]) -> FixResult:
    """Fix stale ADR-270 path references.

    Routing by fix_strategy:
    - "sed": deterministic text replacement for issues with clear canonical paths
    - "report": write structured enforcement report (ambiguous issues)
    - other: delegate to AI CLI for complex fixes
    """
    if ctx.dry_run:
        return FixResult(
            success=True,
            summary=f"Dry run: would process {len(issues)} stale path issue(s)",
        )

    if not issues:
        return FixResult(success=True, summary="No stale path issues to process")

    sed_issues = [i for i in issues if i.get("fix_strategy") == "sed"]
    report_issues = [i for i in issues if i.get("fix_strategy") == "report"]
    ai_issues = [i for i in issues if i.get("fix_strategy") not in ("report", "sed")]

    results: list[FixResult] = []
    if sed_issues:
        results.append(_fix_with_sed(ctx, sed_issues))
    if report_issues:
        results.append(_write_enforcement_report(ctx, report_issues))
    if ai_issues:
        results.append(_fix_with_ai(ctx, ai_issues))

    success = all(result.success for result in results) if results else True
    actions = [action for result in results for action in result.actions]
    changes = [change for result in results for change in result.changes]
    summaries = [result.summary for result in results if result.summary]

    has_code_fixes = any(r.fix_type == "code-fix" for r in results)
    fix_type: str = "code-fix" if has_code_fixes else ("report" if report_issues else "auto")

    return FixResult(
        success=success,
        actions=actions,
        changes=changes,
        summary="; ".join(summaries) if summaries else "No changes made",
        fix_type=fix_type,
    )
