"use client";

import { useEffect, useState, useCallback } from "react";
import {
  X,
  Pin,
  CheckCircle2,
  Layout,
  Sparkles,
  ChevronRight,
} from "lucide-react";
import { toast } from "sonner";

export type DynamicPreviewPayload = {
  id: string;
  title: string;
  type: "strategy" | "checklist" | "data-viz";
  content: any;
  agentName: string;
};

export default function DynamicPreviewModal() {
  const [isOpen, setIsOpen] = useState(false);
  const [payload, setPayload] = useState<DynamicPreviewPayload | null>(null);

  useEffect(() => {
    const handleOpen = (event: CustomEvent<DynamicPreviewPayload>) => {
      setPayload(event.detail);
      setIsOpen(true);
    };

    window.addEventListener("augur:open-dynamic-ui" as any, handleOpen as any);
    return () =>
      window.removeEventListener(
        "augur:open-dynamic-ui" as any,
        handleOpen as any,
      );
  }, []);

  const close = () => {
    setIsOpen(false);
    setTimeout(() => setPayload(null), 200);
  };

  const handlePin = useCallback(() => {
    if (!payload) return;

    toast.success("Pinned to Dashboard", {
      description: `${payload.title} is available to dashboard listeners.`,
    });

    // Preserve the event contract for any dashboard listener that stores pinned previews.
    window.dispatchEvent(
      new CustomEvent("augur:insight-pinned", { detail: payload }),
    );
    close();
  }, [payload]);

  if (!isOpen || !payload) return null;

  return (
    <dialog open className="fixed inset-0 z-[100] m-0 flex h-full max-h-none w-full max-w-none items-center justify-center border-0 bg-black/60 p-4 text-inherit backdrop-blur-md animate-in fade-in duration-300" aria-label={payload.title} onCancel={(e) => { e.preventDefault(); close(); }}>
      <div className="w-full max-w-2xl bg-[var(--bg-card)] border border-[var(--border-color)] rounded-2xl shadow-2xl overflow-hidden glass-panel flex flex-col max-h-[85vh] animate-in zoom-in-95 duration-300">
        {/* Header */}
        <div className="p-6 border-b border-[var(--border-color)] flex items-center justify-between bg-gradient-to-r from-[var(--accent-primary)]/10 to-transparent">
          <div className="flex items-center gap-3">
            <div className="size-10 rounded-xl bg-gradient-to-br from-[var(--accent-primary)] to-[var(--accent-info)] flex items-center justify-center shadow-lg shadow-[var(--accent-primary)]/20">
              <Sparkles className="size-5 text-[var(--accent-foreground,white)] animate-pulse" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-[var(--text-primary)] tracking-tight">
                {payload.title}
              </h2>
              <p className="text-xs text-[var(--text-muted)] font-medium uppercase tracking-wider flex items-center gap-1">
                Generated by{" "}
                <span className="text-[var(--accent-primary)]">
                  {payload.agentName}
                </span>
              </p>
            </div>
          </div>
          <button type="button"
            onClick={close}
            className="p-2 rounded-full hover:bg-[var(--bg-hover)] text-[var(--text-muted)] hover:text-[var(--text-primary)] transition-all"
            aria-label="Close preview"
          >
            <X className="size-5" />
          </button>
        </div>

        {/* Content Area */}
        <div className="flex-1 overflow-y-auto p-8 space-y-6">
          {payload.type === "checklist" && (
            <div className="space-y-3">
              {(payload.content as string[]).map((item) => (
                <div
                  key={item}
                  className="flex items-start gap-4 p-4 rounded-xl bg-[var(--bg-secondary)] border border-[var(--border-color)] group hover:border-[var(--accent-primary)]/30 transition-all cursor-pointer"
                >
                  <div className="mt-0.5">
                    <CheckCircle2 className="size-5 text-[var(--text-muted)] group-hover:text-[var(--accent-success)] transition-colors" />
                  </div>
                  <span className="text-[var(--text-secondary)] group-hover:text-[var(--text-primary)] transition-colors">
                    {item}
                  </span>
                </div>
              ))}
            </div>
          )}

          {payload.type === "strategy" && (
            <div className="prose prose-invert max-w-none">
              <div className="p-6 rounded-2xl bg-[var(--bg-secondary)] border border-[var(--border-color)] relative overflow-hidden">
                <div className="absolute top-0 right-0 p-4 opacity-10">
                  <Layout className="size-24" />
                </div>
                <div className="relative z-10 text-[var(--text-secondary)] leading-relaxed font-light italic">
                  &quot;{payload.content}&quot;
                </div>
              </div>
            </div>
          )}

          {/* Placeholder for Data Viz */}
          {payload.type === "data-viz" && (
            <div className="h-64 flex items-center justify-center border border-dashed border-[var(--border-color)] rounded-2xl bg-[var(--bg-secondary)]">
              <div className="text-center group">
                <Sparkles className="size-12 text-[var(--accent-primary)]/50 mx-auto mb-4 group-hover:scale-110 transition-transform" />
                <p className="text-[var(--text-muted)] text-sm">
                  Interactive visualization rendering…
                </p>
              </div>
            </div>
          )}
        </div>

        {/* Footer Actions */}
        <div className="p-6 border-t border-[var(--border-color)] bg-[var(--bg-primary)]/30 flex items-center justify-between">
          <button type="button"
            onClick={close}
            className="px-6 py-2.5 text-sm font-medium text-[var(--text-muted)] hover:text-[var(--text-primary)] transition-colors"
          >
            Dismiss
          </button>
          <div className="flex gap-3">
            <button type="button"
              onClick={handlePin}
              className="flex items-center gap-2 px-6 py-2.5 bg-[var(--bg-secondary)] hover:bg-[var(--bg-hover)] border border-[var(--border-color)] text-[var(--text-primary)] rounded-xl text-sm font-semibold transition-all"
            >
              <Pin className="size-4 text-[var(--accent-info)]" />
              Pin to Dashboard
            </button>
            <button type="button" className="flex items-center gap-2 px-8 py-2.5 bg-[var(--accent-primary)] hover:opacity-90 text-[var(--accent-foreground,white)] rounded-xl text-sm font-bold shadow-lg shadow-[var(--accent-primary)]/20 transition-all">
              Execute Strategy
              <ChevronRight className="size-4" />
            </button>
          </div>
        </div>
      </div>
    </dialog>
  );
}
