/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * Hub layout for /workspace — provides horizontal tab navigation.
 * Generated by mount-plugins hub assembly.
 */

import type { ReactNode } from 'react';
import { HubTabNav } from '@/components/plugin/HubTabNav';

export default function HubLayout({ children }: { children: ReactNode }) {
  return (
    <div>
      <HubTabNav hubId="workspace" />
      {children}
    </div>
  );
}
