// AUTO-GENERATED by mount-plugins — do not edit

export const PAGES: Record<string, () => Promise<{ default: React.ComponentType }>> = {
  'agents': () => import('@/features/pages/workspace/agents/page'),
  'daily-logs': () => import('@/features/pages/workspace/daily-logs/page'),
  'harness': () => import('@/features/pages/workspace/harness/page'),
  'inbox': () => import('@/features/pages/workspace/inbox/page'),
  'insights': () => import('@/features/pages/workspace/insights/page'),
  'memory': () => import('@/features/pages/workspace/memory/page'),
  'memory-review': () => import('@/features/pages/workspace/memory-review/page'),
  'profile': () => import('@/features/pages/workspace/profile/page'),
  'rag': () => import('@/lib/configs/workspace-rag'),
  'settings': () => import('@/features/pages/workspace/settings/page'),
};
