#!/usr/bin/env python3
"""Write x-augur-type and x-augur-tags to all SKILL.md frontmatter.

Reads the classification report generated by classify_skills.py and adds
x-augur-type + x-augur-tags: [] to each skill's SKILL.md frontmatter.

ADR-463 Task 7.
"""

import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = PROJECT_ROOT / ".claude" / "skills"
REPORT_PATH = PROJECT_ROOT / "docs" / "generated" / "skill-classification-report.md"


def parse_classification_report(report_path: Path) -> dict[str, str]:
    """Parse the markdown report tables to extract {skill_name: type} mapping."""
    text = report_path.read_text()
    mapping: dict[str, str] = {}

    valid_types = {"template", "autoloop", "domain", "runbook", "command", "meta"}

    # Match table rows: | skill_name | type | ... |
    # Works for both "Clean Classifications" and "Flagged for Review" tables
    for match in re.finditer(r"^\|\s*([a-z][a-z0-9_-]*)\s*\|\s*(\w+)\s*\|", text, re.MULTILINE):
        skill_name = match.group(1).strip()
        skill_type = match.group(2).strip()
        # Skip table header rows and summary rows
        if skill_name in ("Skill", "Metric") or skill_type in ("Type", "Count"):
            continue
        if skill_type not in valid_types:
            continue
        mapping[skill_name] = skill_type

    return mapping


def process_skill(skill_dir: Path, augur_type: str) -> str:
    """Add x-augur-type and x-augur-tags to a SKILL.md file.

    Returns: 'updated', 'skipped' (already has type), or 'missing' (no SKILL.md)
    """
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.exists():
        return "missing"

    content = skill_md.read_text()

    # Check if already has x-augur-type
    if "x-augur-type:" in content:
        return "skipped"

    # Split into pre-frontmatter (HTML comments), frontmatter, and body
    # Pattern: optional leading comments, then --- ... ---
    # Handle: <!-- comment -->\n---\n...\n---\n or just ---\n...\n---\n
    prefix = ""
    rest = content

    # Strip leading HTML comments before frontmatter
    while rest.lstrip().startswith("<!--"):
        comment_end = rest.index("-->") + 3
        prefix += rest[:comment_end]
        rest = rest[comment_end:]
        # Also consume the newline after the comment
        if rest.startswith("\n"):
            prefix += "\n"
            rest = rest[1:]

    # Now rest should start with ---
    if not rest.startswith("---"):
        print(f"  WARNING: {skill_dir.name} — no frontmatter found after comments")
        return "error"

    # Find the closing ---
    # First --- is at position 0, find the next ---
    second_marker = rest.index("---", 3)
    frontmatter_block = rest[3:second_marker]  # content between --- markers
    body = rest[second_marker + 3:]

    # Parse frontmatter lines to find insertion point (after name: line)
    fm_lines = frontmatter_block.split("\n")

    # Find the name: line index
    name_line_idx = None
    for i, line in enumerate(fm_lines):
        if line.startswith("name:") or line.startswith("name :"):
            name_line_idx = i
            break

    if name_line_idx is None:
        # If no name: line, insert after description: line
        for i, line in enumerate(fm_lines):
            if line.startswith("description:") or line.startswith("description :"):
                # description might be multi-line (YAML folded/literal), skip continuation lines
                name_line_idx = i
                # Walk past continuation lines (indented or quoted)
                while name_line_idx + 1 < len(fm_lines):
                    next_line = fm_lines[name_line_idx + 1]
                    if next_line and (next_line[0] == " " or next_line[0] == "'"):
                        name_line_idx += 1
                    else:
                        break
                break

    if name_line_idx is None:
        # Last resort: insert at the end of frontmatter
        name_line_idx = len(fm_lines) - 1

    # Insert x-augur-type and x-augur-tags after the name line
    new_lines = [
        f"x-augur-type: {augur_type}",
        "x-augur-tags: []",
    ]
    fm_lines = fm_lines[:name_line_idx + 1] + new_lines + fm_lines[name_line_idx + 1:]

    # Reconstruct
    new_frontmatter = "\n".join(fm_lines)
    new_content = prefix + "---" + new_frontmatter + "---" + body
    skill_md.write_text(new_content)
    return "updated"


def main():
    if not REPORT_PATH.exists():
        print(f"ERROR: Classification report not found at {REPORT_PATH}")
        sys.exit(1)

    mapping = parse_classification_report(REPORT_PATH)
    print(f"Loaded {len(mapping)} skill classifications from report")

    if not mapping:
        print("ERROR: No classifications found in report")
        sys.exit(1)

    stats = {"updated": 0, "skipped": 0, "missing": 0, "error": 0, "not_in_report": 0}

    # Process all skill directories
    skill_dirs = sorted(
        [d for d in SKILLS_DIR.iterdir() if d.is_dir() and (d / "SKILL.md").exists()]
    )

    for skill_dir in skill_dirs:
        skill_name = skill_dir.name
        if skill_name not in mapping:
            stats["not_in_report"] += 1
            print(f"  SKIP {skill_name} — not in classification report")
            continue

        augur_type = mapping[skill_name]
        result = process_skill(skill_dir, augur_type)
        stats[result] += 1
        if result == "updated":
            print(f"  OK   {skill_name} → {augur_type}")
        elif result == "error":
            print(f"  ERR  {skill_name}")
        elif result == "skipped":
            print(f"  SKIP {skill_name} — already has x-augur-type")

    print(f"\nDone. Updated: {stats['updated']}, Skipped: {stats['skipped']}, "
          f"Missing: {stats['missing']}, Errors: {stats['error']}, "
          f"Not in report: {stats['not_in_report']}")

    # Check for skills in report but not on disk
    on_disk = {d.name for d in skill_dirs}
    in_report = set(mapping.keys())
    orphaned = in_report - on_disk
    if orphaned:
        print(f"\nWARNING: {len(orphaned)} skills in report but not on disk: {sorted(orphaned)}")


if __name__ == "__main__":
    main()
