"""Tests for source tag in generated client stubs."""

import importlib.util
import sys
import tempfile
from pathlib import Path
from src.lib.frontmatter_utils import parse_frontmatter

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


def _load_generate_client_stubs():
    module_path = PROJECT_ROOT / "scripts" / "generate_client_stubs.py"
    spec = importlib.util.spec_from_file_location("generate_client_stubs", module_path)
    module = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(module)
    return module


def _create_source_skill(skills_dir: Path, name: str):
    skill_dir = skills_dir / name
    skill_dir.mkdir(parents=True)
    (skill_dir / "SKILL.md").write_text(f"---\nname: {name}\ndescription: test skill\n---\n\nBody.\n")


def test_subdir_stub_has_source_augur():
    """Claude subdir stub should include source: augur in frontmatter."""
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        skills_dir = root / "project-brain" / "capabilities" / "skills"
        _create_source_skill(skills_dir, "my-skill")

        # Create ALL required target directories (the script writes to all clients)
        for d in [
            ".claude/skills",
            ".gemini/skills",
            ".codex/prompts",
            ".cursor/rules",
            ".github/instructions",
            ".opencode/skills",
        ]:
            (root / d).mkdir(parents=True, exist_ok=True)

        module = _load_generate_client_stubs()
        module.generate_and_validate(root, skills_dir)

        stub = root / ".claude" / "skills" / "my-skill" / "SKILL.md"
        assert stub.exists()
        meta, _body = parse_frontmatter(stub)
        assert meta.get("source") == "augur"


def test_codex_flat_stub_is_generated():
    """Codex flat prompt stub should be written to .codex/prompts."""
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        skills_dir = root / "project-brain" / "capabilities" / "skills"
        _create_source_skill(skills_dir, "my-skill")

        for d in [
            ".claude/skills",
            ".gemini/skills",
            ".codex/prompts",
            ".cursor/rules",
            ".github/instructions",
            ".opencode/skills",
        ]:
            (root / d).mkdir(parents=True, exist_ok=True)

        module = _load_generate_client_stubs()
        module.generate_and_validate(root, skills_dir)

        stub = root / ".codex" / "prompts" / "my-skill.md"
        assert stub.exists()
        body = stub.read_text(encoding="utf-8")
        assert "# my-skill" in body
        assert "test skill" in body


def test_opencode_subdir_stub_has_source_augur():
    """OpenCode skill stubs should use the same SKILL.md subdir layout as Claude/Gemini."""
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        skills_dir = root / "project-brain" / "capabilities" / "skills"
        _create_source_skill(skills_dir, "my-skill")

        for d in [
            ".claude/skills",
            ".gemini/skills",
            ".codex/prompts",
            ".cursor/rules",
            ".github/instructions",
            ".opencode/skills",
        ]:
            (root / d).mkdir(parents=True, exist_ok=True)

        module = _load_generate_client_stubs()
        module.generate_and_validate(root, skills_dir)

        stub = root / ".opencode" / "skills" / "my-skill" / "SKILL.md"
        assert stub.exists()
        meta, _body = parse_frontmatter(stub)
        assert meta.get("source") == "augur"


def test_cleanup_does_not_delete_platform_skills():
    """Cleanup should not delete client skills that don't have the AUGUR-GENERATED marker."""
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        (root / ".claude" / "skills" / "platform-tool").mkdir(parents=True)

        # Platform skill — no AUGUR-GENERATED marker
        (root / ".claude" / "skills" / "platform-tool" / "SKILL.md").write_text(
            "---\nname: platform-tool\ndescription: a platform skill\n---\n\nBody.\n"
        )

        module = _load_generate_client_stubs()
        deleted = module.cleanup_stale_stubs(root, existing_names=set())

        # Should NOT be deleted — it's not generated by Augur
        assert len(deleted) == 0
        assert (root / ".claude" / "skills" / "platform-tool" / "SKILL.md").exists()
